import type { VocabEntry } from '../types.ts';

/**
 * People, family and the verbs that take an object (A1 Unit 1).
 *
 * Pre-A1 taught the immediate family as isolated nouns. This unit turns them
 * into something you can say sentences about, which means two new jobs for the
 * vocabulary: it has to support possessives (mein Bruder, deine Schwester) and
 * it has to supply verbs that take a direct object, because the accusative
 * cannot be taught with `haben` alone. A learner who only ever meets the
 * accusative after `haben` learns "haben takes einen", which is the wrong rule.
 *
 * Two kinds of note earn their place here. For the Bulgarian path: where German
 * gender disagrees with Bulgarian, because that is where the article goes
 * wrong — der Junge is "той" in German but "то" in Bulgarian. For the English
 * path: where English has one word and German has two, or where English has no
 * equivalent at all, as with Geschwister.
 */

const U = 'a1-u1';
const L1 = 'a1-u1-l1';
const L2 = 'a1-u1-l2';
const L3 = 'a1-u1-l3';

/* ------------------------------------------------------------------ *
 * Lesson 1 — the wider family
 * ------------------------------------------------------------------ */

const FAMILY: VocabEntry[] = [
  {
    id: 'v-grossmutter',
    german: 'Großmutter',
    display: 'die Großmutter',
    article: 'die',
    gender: 'f',
    plural: 'die Großmütter',
    wordType: 'noun',
    translation: { en: 'grandmother', bg: 'баба' },
    pronunciation: { en: 'GROHS-moo-ter', bg: 'ГРОС-му-тер' },
    example: {
      de: 'Meine Großmutter wohnt in Hamburg.',
      gloss: { en: 'My grandmother lives in Hamburg.', bg: 'Баба ми живее в Хамбург.' },
    },
    tags: ['family'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    related: ['v-oma', 'v-grossvater'],
    notes: {
      en: 'Groß means "big", and it builds the whole generation above: Großmutter, Großvater. The plural takes an umlaut: die Großmütter.',
      bg: 'Groß значи „голям“ и изгражда цялото поколение нагоре: Großmutter, Großvater. Множественото число взима умлаут: die Großmütter.',
    },
  },
  {
    id: 'v-grossvater',
    german: 'Großvater',
    display: 'der Großvater',
    article: 'der',
    gender: 'm',
    plural: 'die Großväter',
    wordType: 'noun',
    translation: { en: 'grandfather', bg: 'дядо' },
    pronunciation: { en: 'GROHS-fah-ter', bg: 'ГРОС-фа-тер' },
    example: {
      de: 'Mein Großvater ist 80 Jahre alt.',
      gloss: { en: 'My grandfather is 80 years old.', bg: 'Дядо ми е на 80 години.' },
    },
    tags: ['family'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    related: ['v-opa', 'v-grossmutter'],
    notes: {
      bg: 'Внимавай: на български „дядо“ звучи като женски род заради -о, но е мъжки. На немски също е мъжки — der Großvater. Тук двата езика съвпадат.',
    },
  },
  {
    id: 'v-oma',
    german: 'Oma',
    display: 'die Oma',
    article: 'die',
    gender: 'f',
    plural: 'die Omas',
    wordType: 'noun',
    translation: { en: 'grandma', bg: 'баба (галено)' },
    pronunciation: { en: 'OH-mah', bg: 'О-ма' },
    example: {
      de: 'Ich besuche meine Oma am Sonntag.',
      gloss: { en: 'I visit my grandma on Sunday.', bg: 'Посещавам баба в неделя.' },
    },
    tags: ['family', 'informal'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
    related: ['v-grossmutter'],
    notes: {
      en: 'This is the word people actually use. Großmutter is what you write on a form; Oma is what you say.',
      bg: 'Това е думата, която хората наистина използват. Großmutter се пише в документи; Oma се казва.',
    },
  },
  {
    id: 'v-opa',
    german: 'Opa',
    display: 'der Opa',
    article: 'der',
    gender: 'm',
    plural: 'die Opas',
    wordType: 'noun',
    translation: { en: 'grandad', bg: 'дядо (галено)' },
    pronunciation: { en: 'OH-pah', bg: 'О-па' },
    example: {
      de: 'Mein Opa kommt aus Österreich.',
      gloss: { en: 'My grandad comes from Austria.', bg: 'Дядо ми е от Австрия.' },
    },
    tags: ['family', 'informal'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
    related: ['v-grossvater'],
  },
  {
    id: 'v-geschwister',
    german: 'Geschwister',
    display: 'die Geschwister',
    article: 'die',
    gender: 'f',
    plural: 'die Geschwister',
    wordType: 'noun',
    translation: { en: 'siblings', bg: 'братя и сестри' },
    pronunciation: { en: 'ge-SHVIS-ter', bg: 'ге-ШВИС-тер' },
    example: {
      de: 'Ich habe zwei Geschwister.',
      gloss: { en: 'I have two siblings.', bg: 'Имам двама братя и сестри.' },
    },
    tags: ['family'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      en: 'Plural only. There is no singular: you cannot say "a Geschwister". If you have one brother, you say "einen Bruder".',
      bg: 'Само в множествено число — точно както българското „братя и сестри“. Немският обаче го казва с една дума, а българският с три.',
    },
  },
  {
    id: 'v-onkel',
    german: 'Onkel',
    display: 'der Onkel',
    article: 'der',
    gender: 'm',
    plural: 'die Onkel',
    wordType: 'noun',
    translation: { en: 'uncle', bg: 'чичо / вуйчо' },
    pronunciation: { en: 'ONG-kel', bg: 'ОН-кел' },
    example: {
      de: 'Mein Onkel arbeitet in Berlin.',
      gloss: { en: 'My uncle works in Berlin.', bg: 'Чичо ми работи в Берлин.' },
    },
    tags: ['family'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Немският има една дума за чичо и вуйчо. Не прави разлика по коя линия е роднината — Onkel върши работа и за двете.',
      en: 'The plural is identical to the singular: der Onkel, die Onkel. Only the article tells you which you mean.',
    },
  },
  {
    id: 'v-tante',
    german: 'Tante',
    display: 'die Tante',
    article: 'die',
    gender: 'f',
    plural: 'die Tanten',
    wordType: 'noun',
    translation: { en: 'aunt', bg: 'леля' },
    pronunciation: { en: 'TAHN-te', bg: 'ТАН-те' },
    example: {
      de: 'Meine Tante heißt Maria.',
      gloss: { en: 'My aunt is called Maria.', bg: 'Леля ми се казва Мария.' },
    },
    tags: ['family'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-junge',
    german: 'Junge',
    display: 'der Junge',
    article: 'der',
    gender: 'm',
    plural: 'die Jungen',
    wordType: 'noun',
    translation: { en: 'boy', bg: 'момче' },
    pronunciation: { en: 'YOONG-e', bg: 'ЮН-ге' },
    example: {
      de: 'Der Junge ist mein Sohn.',
      gloss: { en: 'The boy is my son.', bg: 'Момчето е синът ми.' },
    },
    tags: ['people'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    related: ['v-maedchen'],
    notes: {
      bg: 'Тук родовете се разминават: „момче“ е среден род на български, но der Junge е мъжки на немски. Пиши der, не das — колкото и да звучи странно.',
      en: 'Note the pair: der Junge is masculine as you would expect, but das Mädchen is neuter, which you would not.',
    },
  },
  {
    id: 'v-baby',
    german: 'Baby',
    display: 'das Baby',
    article: 'das',
    gender: 'n',
    plural: 'die Babys',
    wordType: 'noun',
    translation: { en: 'baby', bg: 'бебе' },
    pronunciation: { en: 'BAY-bee', bg: 'БЕЙ-би' },
    example: {
      de: 'Das Baby schläft.',
      gloss: { en: 'The baby is sleeping.', bg: 'Бебето спи.' },
    },
    tags: ['family', 'people'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
    notes: {
      bg: 'Тук родовете съвпадат — и двата езика са среден род. Множественото число е с -s, което е рядко в немския: die Babys.',
    },
  },
  {
    id: 'v-mensch',
    german: 'Mensch',
    display: 'der Mensch',
    article: 'der',
    gender: 'm',
    plural: 'die Menschen',
    wordType: 'noun',
    translation: { en: 'person, human being', bg: 'човек' },
    pronunciation: { en: 'mensh', bg: 'менш' },
    example: {
      de: 'Sie ist ein netter Mensch.',
      gloss: { en: 'She is a nice person.', bg: 'Тя е добър човек.' },
    },
    tags: ['people'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      en: 'Mensch is a human being regardless of sex, and it stays masculine even about a woman: "Sie ist ein netter Mensch."',
      bg: 'Mensch е човек независимо от пола и остава мъжки род дори за жена — точно както „човек“ на български: „Тя е добър човек“.',
    },
  },
  {
    id: 'v-verheiratet',
    german: 'verheiratet',
    display: 'verheiratet',
    wordType: 'adjective',
    translation: { en: 'married', bg: 'женен / омъжена' },
    pronunciation: { en: 'fer-HY-rah-tet', bg: 'фер-ХАЙ-ра-тет' },
    example: {
      de: 'Meine Schwester ist verheiratet.',
      gloss: { en: 'My sister is married.', bg: 'Сестра ми е омъжена.' },
    },
    tags: ['people', 'status'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Една дума за двата пола. Българският сменя думата — „женен“ за мъж, „омъжена“ за жена — а немският използва verheiratet и за двамата.',
    },
  },
  {
    id: 'v-ledig',
    german: 'ledig',
    display: 'ledig',
    wordType: 'adjective',
    translation: { en: 'single, unmarried', bg: 'неженен / неомъжена' },
    pronunciation: { en: 'LAY-dikh', bg: 'ЛЕ-дих' },
    example: {
      de: 'Ich bin ledig.',
      gloss: { en: 'I am single.', bg: 'Не съм женен.' },
    },
    tags: ['people', 'status'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'This is the word on official forms. In conversation people more often say "Ich bin Single".',
      bg: 'Това е думата в официалните формуляри. В разговор по-често се казва „Ich bin Single“.',
    },
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 2 — verbs with an object, and the people you meet
 * ------------------------------------------------------------------ */

const OBJECT_VERBS: VocabEntry[] = [
  {
    id: 'v-kennen',
    german: 'kennen',
    display: 'kennen',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'gekannt' },
    translation: { en: 'to know (a person or place)', bg: 'познавам' },
    pronunciation: { en: 'KEN-nen', bg: 'КЕ-нен' },
    example: {
      de: 'Ich kenne deinen Bruder.',
      gloss: { en: 'I know your brother.', bg: 'Познавам брат ти.' },
    },
    tags: ['verb', 'accusative'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'German splits English "know" in two. kennen is being acquainted with a person or place; wissen is knowing a fact. "Ich kenne Berlin" but "Ich weiß das".',
      bg: 'kennen е „познавам“ — човек или място. За факт немският използва друг глагол, wissen. Българският прави същото разграничение: „познавам Иван“ срещу „знам, че…“.',
    },
  },
  {
    id: 'v-sehen',
    german: 'sehen',
    display: 'sehen',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'gesehen' },
    translation: { en: 'to see', bg: 'виждам' },
    pronunciation: { en: 'ZAY-en', bg: 'ЗЕ-ен' },
    example: {
      de: 'Ich sehe meinen Vater jeden Tag.',
      gloss: { en: 'I see my father every day.', bg: 'Виждам баща си всеки ден.' },
    },
    tags: ['verb', 'accusative', 'irregular'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'Irregular in the du and er/sie/es forms: du siehst, er sieht. The e becomes ie.',
      bg: 'Неправилен при du и er/sie/es: du siehst, er sieht. Гласната e става ie.',
    },
  },
  {
    id: 'v-suchen',
    german: 'suchen',
    display: 'suchen',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'gesucht' },
    translation: { en: 'to look for', bg: 'търся' },
    pronunciation: { en: 'ZOO-khen', bg: 'ЗУ-хен' },
    example: {
      de: 'Ich suche meine Schwester.',
      gloss: { en: 'I am looking for my sister.', bg: 'Търся сестра си.' },
    },
    tags: ['verb', 'accusative'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'One word where English needs two: suchen already means "look for", so there is no preposition after it.',
      bg: 'Никакъв предлог след него: „търся нещо“, suchen etwas. Немският тук е по-прост от английския.',
    },
  },
  {
    id: 'v-brauchen',
    german: 'brauchen',
    display: 'brauchen',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'gebraucht' },
    translation: { en: 'to need', bg: 'трябва ми, нуждая се от' },
    pronunciation: { en: 'BROW-khen', bg: 'БРАУ-хен' },
    example: {
      de: 'Ich brauche einen Tisch.',
      gloss: { en: 'I need a table.', bg: 'Трябва ми маса.' },
    },
    tags: ['verb', 'accusative'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      bg: 'Внимавай със строежа на изречението. Българският казва „трябва ми стол“ — столът е подлог. Немският казва „ich brauche einen Stuhl“ — аз съм подлогът, а столът е допълнение и затова е einen.',
    },
  },
  {
    id: 'v-besuchen',
    german: 'besuchen',
    display: 'besuchen',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'besucht' },
    translation: { en: 'to visit', bg: 'посещавам, гостувам на' },
    pronunciation: { en: 'be-ZOO-khen', bg: 'бе-ЗУ-хен' },
    example: {
      de: 'Wir besuchen meine Eltern.',
      gloss: { en: 'We are visiting my parents.', bg: 'Гостуваме на родителите ми.' },
    },
    tags: ['verb', 'accusative'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      bg: 'Българското „гостувам на някого“ иска предлог. Немското besuchen не иска нищо — човекът е пряко допълнение: besuchen meine Oma.',
    },
  },
  {
    id: 'v-finden',
    german: 'finden',
    display: 'finden',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'gefunden' },
    translation: { en: 'to find; to think (of something)', bg: 'намирам; мисля (за нещо)' },
    pronunciation: { en: 'FIN-den', bg: 'ФИН-ден' },
    example: {
      de: 'Ich finde das Buch gut.',
      gloss: { en: 'I think the book is good.', bg: 'Намирам книгата за добра.' },
    },
    tags: ['verb', 'accusative'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'Also the everyday way to give an opinion: "Ich finde das gut" is "I think that’s good", not "I find that good".',
      bg: 'Освен „намирам“, това е всекидневният начин да кажеш мнение: „Ich finde das gut“ — „Мисля, че е добре“.',
    },
  },
  {
    id: 'v-moegen',
    german: 'mögen',
    display: 'mögen',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'gemocht' },
    translation: { en: 'to like', bg: 'харесвам' },
    pronunciation: { en: 'MOE-gen', bg: 'МЬО-ген' },
    example: {
      de: 'Ich mag meinen Beruf.',
      gloss: { en: 'I like my job.', bg: 'Харесвам професията си.' },
    },
    tags: ['verb', 'accusative', 'irregular'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    notes: {
      en: 'The ich form drops the -en and the umlaut: ich mag, du magst, er mag. Note there is no -t on the er form.',
      bg: 'Формата за ich е неочаквана: ich mag, du magst, er mag — без умлаут и без -t при er.',
    },
  },
  {
    id: 'v-freund',
    german: 'Freund',
    display: 'der Freund',
    article: 'der',
    gender: 'm',
    plural: 'die Freunde',
    wordType: 'noun',
    translation: { en: 'friend; boyfriend', bg: 'приятел; гадже (мъж)' },
    pronunciation: { en: 'froynt', bg: 'фройнт' },
    example: {
      de: 'Ich besuche meinen Freund.',
      gloss: { en: 'I am visiting my friend.', bg: 'Отивам на гости на приятеля си.' },
    },
    tags: ['people'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    related: ['v-freundin'],
    notes: {
      en: 'Ambiguous in the same way as in English: "mein Freund" usually means boyfriend, while "ein Freund von mir" is just a friend.',
      bg: 'Двусмислено, точно както на български: „mein Freund“ обикновено значи „гаджето ми“, а „ein Freund von mir“ е просто „един приятел“.',
    },
  },
  {
    id: 'v-freundin',
    german: 'Freundin',
    display: 'die Freundin',
    article: 'die',
    gender: 'f',
    plural: 'die Freundinnen',
    wordType: 'noun',
    translation: { en: 'friend (female); girlfriend', bg: 'приятелка; гадже (жена)' },
    pronunciation: { en: 'FROYN-din', bg: 'ФРОЙН-дин' },
    example: {
      de: 'Meine Freundin heißt Lena.',
      gloss: { en: 'My girlfriend is called Lena.', bg: 'Приятелката ми се казва Лена.' },
    },
    tags: ['people'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-freund'],
    notes: {
      en: 'The -in ending makes the feminine form, and the plural doubles the n: Freundinnen. You met the same pattern with Lehrer / Lehrerin.',
      bg: 'Окончанието -in прави женската форма, а множественото удвоява n: Freundinnen. Същият модел като Lehrer / Lehrerin.',
    },
  },
  {
    id: 'v-kollege',
    german: 'Kollege',
    display: 'der Kollege',
    article: 'der',
    gender: 'm',
    plural: 'die Kollegen',
    wordType: 'noun',
    translation: { en: 'colleague (male)', bg: 'колега' },
    pronunciation: { en: 'ko-LAY-ge', bg: 'ко-ЛЕ-ге' },
    example: {
      de: 'Ich kenne deinen Kollegen.',
      gloss: { en: 'I know your colleague.', bg: 'Познавам колегата ти.' },
    },
    tags: ['people', 'work'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    related: ['v-kollegin'],
    notes: {
      en: 'One of a small group of masculine nouns that add -n when they are the object: der Kollege, but "Ich kenne den Kollegen". Recognise it for now; the pattern is drilled later.',
      bg: 'Една от малкото мъжки думи, които добавят -n като допълнение: der Kollege, но „Ich kenne den Kollegen“. Засега само го разпознавай.',
    },
  },
  {
    id: 'v-kollegin',
    german: 'Kollegin',
    display: 'die Kollegin',
    article: 'die',
    gender: 'f',
    plural: 'die Kolleginnen',
    wordType: 'noun',
    translation: { en: 'colleague (female)', bg: 'колежка' },
    pronunciation: { en: 'ko-LAY-gin', bg: 'ко-ЛЕ-гин' },
    example: {
      de: 'Meine Kollegin kommt aus Polen.',
      gloss: { en: 'My colleague comes from Poland.', bg: 'Колежката ми е от Полша.' },
    },
    tags: ['people', 'work'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-kollege'],
  },
  {
    id: 'v-nachbar',
    german: 'Nachbar',
    display: 'der Nachbar',
    article: 'der',
    gender: 'm',
    plural: 'die Nachbarn',
    wordType: 'noun',
    translation: { en: 'neighbour', bg: 'съсед' },
    pronunciation: { en: 'NAHKH-bar', bg: 'НАХ-бар' },
    example: {
      de: 'Mein Nachbar ist sehr nett.',
      gloss: { en: 'My neighbour is very nice.', bg: 'Съседът ми е много мил.' },
    },
    tags: ['people'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'Like Kollege, this one adds -n as an object: "Ich kenne meinen Nachbarn."',
      bg: 'Като Kollege — добавя -n като допълнение: „Ich kenne meinen Nachbarn“.',
    },
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 3 — describing people
 * ------------------------------------------------------------------ */

const DESCRIBING: VocabEntry[] = [
  {
    id: 'v-nett',
    german: 'nett',
    display: 'nett',
    wordType: 'adjective',
    translation: { en: 'nice, kind', bg: 'мил, любезен' },
    pronunciation: { en: 'net', bg: 'нет' },
    example: {
      de: 'Seine Schwester ist sehr nett.',
      gloss: { en: 'His sister is very nice.', bg: 'Сестра му е много мила.' },
    },
    tags: ['adjective', 'people'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 1,
    notes: {
      en: 'The default compliment about a person. "Nett" is warm but unremarkable — closer to "kind" than to "lovely".',
      bg: 'Най-обикновената похвала за човек. „Nett“ е топло, но не възторжено — по-скоро „мил“, отколкото „прекрасен“.',
    },
  },
  {
    id: 'v-freundlich',
    german: 'freundlich',
    display: 'freundlich',
    wordType: 'adjective',
    translation: { en: 'friendly', bg: 'приятелски, любезен' },
    pronunciation: { en: 'FROYNT-likh', bg: 'ФРОЙНТ-лих' },
    example: {
      de: 'Meine Kollegin ist freundlich.',
      gloss: { en: 'My colleague is friendly.', bg: 'Колежката ми е любезна.' },
    },
    tags: ['adjective', 'people'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    related: ['v-freund'],
    notes: {
      en: 'Built from Freund plus -lich, the same way English builds "friendly" from "friend". When you meet a long German word, look for the short one inside it.',
      bg: 'Съставено от Freund плюс -lich. Когато видиш дълга немска дума, търси късата вътре в нея — това е най-полезният навик в немския.',
    },
  },
  {
    id: 'v-lustig',
    german: 'lustig',
    display: 'lustig',
    wordType: 'adjective',
    translation: { en: 'funny, cheerful', bg: 'весел, забавен' },
    pronunciation: { en: 'LOOS-tikh', bg: 'ЛУС-тих' },
    example: {
      de: 'Mein Opa ist sehr lustig.',
      gloss: { en: 'My grandad is very funny.', bg: 'Дядо ми е много забавен.' },
    },
    tags: ['adjective', 'people'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-ruhig',
    german: 'ruhig',
    display: 'ruhig',
    wordType: 'adjective',
    translation: { en: 'quiet, calm', bg: 'тих, спокоен' },
    pronunciation: { en: 'ROO-ikh', bg: 'РУ-их' },
    example: {
      de: 'Ihre Tochter ist sehr ruhig.',
      gloss: { en: 'Her daughter is very quiet.', bg: 'Дъщеря ѝ е много тиха.' },
    },
    tags: ['adjective', 'people'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-klug',
    german: 'klug',
    display: 'klug',
    wordType: 'adjective',
    translation: { en: 'clever, intelligent', bg: 'умен' },
    pronunciation: { en: 'klook', bg: 'клук' },
    example: {
      de: 'Ihr Sohn ist sehr klug.',
      gloss: { en: 'Her son is very clever.', bg: 'Синът ѝ е много умен.' },
    },
    tags: ['adjective', 'people'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-jung',
    german: 'jung',
    display: 'jung',
    wordType: 'adjective',
    translation: { en: 'young', bg: 'млад' },
    pronunciation: { en: 'yoong', bg: 'юнг' },
    example: {
      de: 'Meine Eltern sind noch jung.',
      gloss: { en: 'My parents are still young.', bg: 'Родителите ми са още млади.' },
    },
    tags: ['adjective', 'people'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 1,
    related: ['v-alt'],
    notes: {
      en: 'The opposite of alt, which you already know. Learning adjectives in pairs is worth the small extra effort.',
      bg: 'Противоположното на alt, което вече знаеш. Прилагателните се учат по двойки — струва си малкото допълнително усилие.',
    },
  },
  {
    id: 'v-streng',
    german: 'streng',
    display: 'streng',
    wordType: 'adjective',
    translation: { en: 'strict', bg: 'строг' },
    pronunciation: { en: 'shtreng', bg: 'щренг' },
    example: {
      de: 'Mein Vater ist streng.',
      gloss: { en: 'My father is strict.', bg: 'Баща ми е строг.' },
    },
    tags: ['adjective', 'people'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    notes: {
      bg: 'Обърни внимание на st- в началото: на немски се чете „щ“, не „ст“. Затова streng звучи като „щренг“.',
      en: 'Remember that st- at the start of a German word is pronounced "sht": streng sounds like "shtreng".',
    },
  },
  {
    id: 'v-zusammen',
    german: 'zusammen',
    display: 'zusammen',
    wordType: 'adverb',
    translation: { en: 'together', bg: 'заедно' },
    pronunciation: { en: 'tsoo-ZAH-men', bg: 'цу-ЗА-мен' },
    example: {
      de: 'Wir wohnen zusammen.',
      gloss: { en: 'We live together.', bg: 'Живеем заедно.' },
    },
    tags: ['adverb'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-sehr',
    german: 'sehr',
    display: 'sehr',
    wordType: 'adverb',
    translation: { en: 'very', bg: 'много' },
    pronunciation: { en: 'zayr', bg: 'зер' },
    example: {
      de: 'Meine Oma ist sehr nett.',
      gloss: { en: 'My grandma is very nice.', bg: 'Баба ми е много мила.' },
    },
    tags: ['adverb'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 1,
    notes: {
      bg: 'Внимавай: българското „много“ върши две работи — „много мил“ (sehr nett) и „много хора“ (viele Menschen). Немският ги разделя: sehr пред прилагателно, viel(e) пред съществително.',
      en: 'sehr goes in front of an adjective or adverb only. For "a lot of" with a noun, German uses viel or viele.',
    },
  },
  {
    id: 'v-person',
    german: 'Person',
    display: 'die Person',
    article: 'die',
    gender: 'f',
    plural: 'die Personen',
    wordType: 'noun',
    translation: { en: 'person', bg: 'човек, лице' },
    pronunciation: { en: 'per-ZOHN', bg: 'пер-ЗОН' },
    example: {
      de: 'Wir sind vier Personen.',
      gloss: { en: 'There are four of us.', bg: 'Ние сме четирима.' },
    },
    tags: ['people'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    notes: {
      en: 'Always feminine, even about a man: "Er ist eine nette Person." The word for counting people in restaurants and hotels.',
      bg: 'Винаги женски род, дори за мъж: „Er ist eine nette Person“. Думата, с която се броят хора в ресторант или хотел.',
    },
  },
];

export const FAMILY_VOCAB: VocabEntry[] = [...FAMILY, ...OBJECT_VERBS, ...DESCRIBING];
