import type { VocabEntry } from '../types.ts';

/**
 * Food, cafés and shopping (A1 Unit 3).
 *
 * This is the first unit whose vocabulary a learner will use within a day of
 * learning it, so the selection is ruthlessly practical: what is on a German
 * breakfast table, what you say to a waiter, and what you say at a till. Words
 * that are common in textbooks but rare in a shop are left out.
 *
 * Two pedagogical threads run through the notes. Gender is chosen to keep the
 * accusative working — you order things, and ordering a masculine noun means
 * einen — and the Bulgarian notes concentrate on the places where a shop
 * transaction goes wrong: the quantity phrases, which Bulgarian builds with a
 * preposition ("килограм ябълки" is fine, but "чаша от кафе" is not what German
 * does either), and the politeness level, which is not optional in a German
 * shop the way it can be in a Bulgarian one.
 */

const U = 'a1-u3';
const L1 = 'a1-u3-l1';
const L2 = 'a1-u3-l2';
const L3 = 'a1-u3-l3';

/* ------------------------------------------------------------------ *
 * Lesson 1 — food and drink
 * ------------------------------------------------------------------ */

const FOOD: VocabEntry[] = [
  {
    id: 'v-brot',
    german: 'Brot',
    display: 'das Brot',
    article: 'das',
    gender: 'n',
    plural: 'die Brote',
    wordType: 'noun',
    translation: { en: 'bread', bg: 'хляб' },
    pronunciation: { en: 'broht', bg: 'брот' },
    example: {
      de: 'Ich esse Brot mit Butter.',
      gloss: { en: 'I eat bread with butter.', bg: 'Ям хляб с масло.' },
    },
    tags: ['food'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
    notes: {
      bg: 'Родовете се разминават: „хляб“ е мъжки род, а das Brot е среден. И забележи, че немският не слага член, когато говори за храна изобщо: „Ich esse Brot“, не „das Brot“.',
      en: 'German drops the article when talking about food in general: "Ich esse Brot", not "I eat the bread".',
    },
  },
  {
    id: 'v-butter',
    german: 'Butter',
    display: 'die Butter',
    article: 'die',
    gender: 'f',
    wordType: 'noun',
    translation: { en: 'butter', bg: 'масло' },
    pronunciation: { en: 'BOO-ter', bg: 'БУ-тер' },
    example: {
      de: 'Die Butter ist im Kühlschrank.',
      gloss: { en: 'The butter is in the fridge.', bg: 'Маслото е в хладилника.' },
    },
    tags: ['food'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'Feminine in German, which surprises English speakers who expect no gender at all — but it is one of the few food words where the article is worth drilling, because it appears on every shopping list.',
      bg: 'Женски род на немски, а „масло“ е среден на български. Още едно разминаване за запомняне заедно с члена.',
    },
  },
  {
    id: 'v-kaese',
    german: 'Käse',
    display: 'der Käse',
    article: 'der',
    gender: 'm',
    wordType: 'noun',
    translation: { en: 'cheese', bg: 'сирене, кашкавал' },
    pronunciation: { en: 'KAY-ze', bg: 'КЕ-зе' },
    example: {
      de: 'Ich nehme den Käse.',
      gloss: { en: 'I will take the cheese.', bg: 'Ще взема сиренето.' },
    },
    tags: ['food'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Немският има една дума за сирене и кашкавал. Ако трябва да уточниш, се описва — но в магазин Käse е достатъчно.',
    },
  },
  {
    id: 'v-milch',
    german: 'Milch',
    display: 'die Milch',
    article: 'die',
    gender: 'f',
    wordType: 'noun',
    translation: { en: 'milk', bg: 'мляко' },
    pronunciation: { en: 'milkh', bg: 'милх' },
    example: {
      de: 'Ich trinke Milch.',
      gloss: { en: 'I drink milk.', bg: 'Пия мляко.' },
    },
    tags: ['food', 'drink'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-kaffee',
    german: 'Kaffee',
    display: 'der Kaffee',
    article: 'der',
    gender: 'm',
    plural: 'die Kaffees',
    wordType: 'noun',
    translation: { en: 'coffee', bg: 'кафе' },
    pronunciation: { en: 'KAH-fay', bg: 'КА-фе' },
    example: {
      de: 'Ich möchte einen Kaffee, bitte.',
      gloss: { en: 'I would like a coffee, please.', bg: 'Бих искал едно кафе, моля.' },
    },
    tags: ['drink'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Внимание с рода: „кафе“ е среден род на български, а der Kaffee е мъжки. Това има пряко значение при поръчка — „einen Kaffee“, не „ein Kaffee“.',
      en: 'Masculine, which matters the moment you order one: einen Kaffee.',
    },
  },
  {
    id: 'v-tee',
    german: 'Tee',
    display: 'der Tee',
    article: 'der',
    gender: 'm',
    plural: 'die Tees',
    wordType: 'noun',
    translation: { en: 'tea', bg: 'чай' },
    pronunciation: { en: 'tay', bg: 'те' },
    example: {
      de: 'Trinkst du Tee?',
      gloss: { en: 'Do you drink tea?', bg: 'Пиеш ли чай?' },
    },
    tags: ['drink'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-apfel',
    german: 'Apfel',
    display: 'der Apfel',
    article: 'der',
    gender: 'm',
    plural: 'die Äpfel',
    wordType: 'noun',
    translation: { en: 'apple', bg: 'ябълка' },
    pronunciation: { en: 'AHP-fel', bg: 'АП-фел' },
    example: {
      de: 'Ich kaufe einen Apfel.',
      gloss: { en: 'I am buying an apple.', bg: 'Купувам една ябълка.' },
    },
    tags: ['food'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'The plural changes only by an umlaut: der Apfel, die Äpfel. Nothing is added.',
      bg: 'Множественото се прави само с умлаут: der Apfel, die Äpfel. Нищо не се добавя. И пак разминаване в рода — „ябълка“ е женски род.',
    },
  },
  {
    id: 'v-tomate',
    german: 'Tomate',
    display: 'die Tomate',
    article: 'die',
    gender: 'f',
    plural: 'die Tomaten',
    wordType: 'noun',
    translation: { en: 'tomato', bg: 'домат' },
    pronunciation: { en: 'to-MAH-te', bg: 'то-МА-те' },
    example: {
      de: 'Ich brauche drei Tomaten.',
      gloss: { en: 'I need three tomatoes.', bg: 'Трябват ми три домата.' },
    },
    tags: ['food'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Родът пак не съвпада: „домат“ е мъжки, die Tomate е женски.',
    },
  },
  {
    id: 'v-kartoffel',
    german: 'Kartoffel',
    display: 'die Kartoffel',
    article: 'die',
    gender: 'f',
    plural: 'die Kartoffeln',
    wordType: 'noun',
    translation: { en: 'potato', bg: 'картоф' },
    pronunciation: { en: 'kar-TOF-fel', bg: 'кар-ТО-фел' },
    example: {
      de: 'Wir kaufen Kartoffeln.',
      gloss: { en: 'We are buying potatoes.', bg: 'Купуваме картофи.' },
    },
    tags: ['food'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
  },
  {
    id: 'v-ei',
    german: 'Ei',
    display: 'das Ei',
    article: 'das',
    gender: 'n',
    plural: 'die Eier',
    wordType: 'noun',
    translation: { en: 'egg', bg: 'яйце' },
    pronunciation: { en: 'eye', bg: 'ай' },
    example: {
      de: 'Ich esse ein Ei zum Frühstück.',
      gloss: { en: 'I eat an egg for breakfast.', bg: 'Ям яйце за закуска.' },
    },
    tags: ['food'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'The plural is irregular and very common: die Eier.',
      bg: 'Множественото е неправилно и много често срещано: die Eier.',
    },
  },
  {
    id: 'v-fleisch',
    german: 'Fleisch',
    display: 'das Fleisch',
    article: 'das',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'meat', bg: 'месо' },
    pronunciation: { en: 'flysh', bg: 'флайш' },
    example: {
      de: 'Ich esse kein Fleisch.',
      gloss: { en: 'I do not eat meat.', bg: 'Не ям месо.' },
    },
    tags: ['food'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'A useful sentence to own early: "Ich esse kein Fleisch." Note kein, not nicht — German negates a noun with kein.',
      bg: 'Изречение, което си струва да знаеш рано: „Ich esse kein Fleisch“. Забележи kein, а не nicht — немският отрича съществителното с kein.',
    },
  },
  {
    id: 'v-suppe',
    german: 'Suppe',
    display: 'die Suppe',
    article: 'die',
    gender: 'f',
    plural: 'die Suppen',
    wordType: 'noun',
    translation: { en: 'soup', bg: 'супа' },
    pronunciation: { en: 'ZOO-pe', bg: 'ЗУ-пе' },
    example: {
      de: 'Die Suppe ist sehr gut.',
      gloss: { en: 'The soup is very good.', bg: 'Супата е много добра.' },
    },
    tags: ['food'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-kuchen',
    german: 'Kuchen',
    display: 'der Kuchen',
    article: 'der',
    gender: 'm',
    plural: 'die Kuchen',
    wordType: 'noun',
    translation: { en: 'cake', bg: 'сладкиш, кекс' },
    pronunciation: { en: 'KOO-khen', bg: 'КУ-хен' },
    example: {
      de: 'Ich möchte einen Kuchen.',
      gloss: { en: 'I would like a cake.', bg: 'Бих искал един сладкиш.' },
    },
    tags: ['food'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    related: ['v-kueche'],
    notes: {
      en: 'Not to be confused with die Küche, the kitchen. One umlaut apart, and the pair is a classic mix-up.',
      bg: 'Да не се бърка с die Küche — кухнята. Разликата е един умлаут и объркването е класическо.',
    },
  },
  {
    id: 'v-hungrig',
    german: 'hungrig',
    display: 'hungrig',
    wordType: 'adjective',
    translation: { en: 'hungry', bg: 'гладен' },
    pronunciation: { en: 'HOONG-rikh', bg: 'ХУН-грих' },
    example: {
      de: 'Ich bin hungrig.',
      gloss: { en: 'I am hungry.', bg: 'Гладен съм.' },
    },
    tags: ['adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'German says "Ich bin hungrig" or, more often, "Ich habe Hunger" — I have hunger. Both are normal.',
      bg: 'Немският казва „Ich bin hungrig“ или, по-често, „Ich habe Hunger“ — имам глад. И двете са нормални.',
    },
  },
  {
    id: 'v-lecker',
    german: 'lecker',
    display: 'lecker',
    wordType: 'adjective',
    translation: { en: 'tasty, delicious', bg: 'вкусен' },
    pronunciation: { en: 'LEK-ker', bg: 'ЛЕ-кер' },
    example: {
      de: 'Der Kuchen ist sehr lecker.',
      gloss: { en: 'The cake is very tasty.', bg: 'Сладкишът е много вкусен.' },
    },
    tags: ['adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
    notes: {
      en: 'The word Germans actually use about food. "Gut" is faint praise for a meal; "lecker" is the compliment.',
      bg: 'Думата, която немците наистина използват за храна. „Gut“ е слаба похвала за ядене; „lecker“ е истинският комплимент.',
    },
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 2 — in a café
 * ------------------------------------------------------------------ */

const CAFE: VocabEntry[] = [
  {
    id: 'v-moechten',
    german: 'möchten',
    display: 'möchten',
    wordType: 'verb',
    translation: { en: 'would like', bg: 'бих искал' },
    pronunciation: { en: 'MOEKH-ten', bg: 'МЬОХ-тен' },
    example: {
      de: 'Ich möchte einen Kaffee.',
      gloss: { en: 'I would like a coffee.', bg: 'Бих искал едно кафе.' },
    },
    tags: ['verb', 'modal', 'politeness'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    related: ['v-wollen'],
    notes: {
      en: 'The polite way to ask for something. "Ich will einen Kaffee" is grammatically fine and sounds like a demand; "Ich möchte" is what you say in a shop.',
      bg: 'Учтивият начин да поискаш нещо. „Ich will einen Kaffee“ е граматически вярно, но звучи като заповед; в магазин или кафене се казва „Ich möchte“.',
    },
  },
  {
    id: 'v-nehmen',
    german: 'nehmen',
    display: 'nehmen',
    wordType: 'verb',
    translation: { en: 'to take, to have (ordering)', bg: 'вземам' },
    pronunciation: { en: 'NAY-men', bg: 'НЕ-мен' },
    example: {
      de: 'Ich nehme die Suppe.',
      gloss: { en: 'I will have the soup.', bg: 'Ще взема супата.' },
    },
    tags: ['verb', 'accusative'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    notes: {
      en: 'Irregular: du nimmst, er nimmt. It is also the normal verb for ordering — "Ich nehme die Suppe" is how you say "I will have the soup".',
      bg: 'Неправилен: du nimmst, er nimmt. Това е и обичайният глагол при поръчка — „Ich nehme die Suppe“ значи „Ще взема супата“.',
    },
  },
  {
    id: 'v-bezahlen',
    german: 'bezahlen',
    display: 'bezahlen',
    wordType: 'verb',
    translation: { en: 'to pay', bg: 'плащам' },
    pronunciation: { en: 'be-TSAH-len', bg: 'бе-ЦА-лен' },
    example: {
      de: 'Ich möchte bezahlen, bitte.',
      gloss: { en: 'I would like to pay, please.', bg: 'Бих искал да платя, моля.' },
    },
    tags: ['verb', 'money'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: '"Ich möchte bezahlen, bitte" is the whole sentence you need to end a meal. Learn it as one block.',
      bg: '„Ich möchte bezahlen, bitte“ е цялото изречение, с което приключваш едно ядене. Научи го наведнъж.',
    },
  },
  {
    id: 'v-rechnung',
    german: 'Rechnung',
    display: 'die Rechnung',
    article: 'die',
    gender: 'f',
    plural: 'die Rechnungen',
    wordType: 'noun',
    translation: { en: 'bill, invoice', bg: 'сметка' },
    pronunciation: { en: 'REKH-noong', bg: 'РЕХ-нунг' },
    example: {
      de: 'Die Rechnung, bitte.',
      gloss: { en: 'The bill, please.', bg: 'Сметката, моля.' },
    },
    tags: ['money', 'cafe'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
  },
  {
    id: 'v-speisekarte',
    german: 'Speisekarte',
    display: 'die Speisekarte',
    article: 'die',
    gender: 'f',
    plural: 'die Speisekarten',
    wordType: 'noun',
    translation: { en: 'menu', bg: 'меню' },
    pronunciation: { en: 'SHPY-ze-kar-te', bg: 'ШПАЙ-зе-кар-те' },
    example: {
      de: 'Die Speisekarte, bitte.',
      gloss: { en: 'The menu, please.', bg: 'Менюто, моля.' },
    },
    tags: ['cafe'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'Speise (dish) plus Karte (card). Germans also just say "die Karte".',
      bg: 'Speise (ястие) плюс Karte (карта). Немците често казват просто „die Karte“.',
    },
  },
  {
    id: 'v-kellner',
    german: 'Kellner',
    display: 'der Kellner',
    article: 'der',
    gender: 'm',
    plural: 'die Kellner',
    wordType: 'noun',
    translation: { en: 'waiter', bg: 'сервитьор' },
    pronunciation: { en: 'KEL-ner', bg: 'КЕЛ-нер' },
    example: {
      de: 'Der Kellner kommt gleich.',
      gloss: { en: 'The waiter is coming shortly.', bg: 'Сервитьорът идва веднага.' },
    },
    tags: ['cafe', 'people', 'work'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'The feminine is die Kellnerin, built with the same -in you met with Lehrerin and Freundin.',
      bg: 'Женската форма е die Kellnerin, с познатото -in както при Lehrerin и Freundin.',
    },
  },
  {
    id: 'v-glas',
    german: 'Glas',
    display: 'das Glas',
    article: 'das',
    gender: 'n',
    plural: 'die Gläser',
    wordType: 'noun',
    translation: { en: 'glass', bg: 'чаша (стъклена)' },
    pronunciation: { en: 'glahs', bg: 'глас' },
    example: {
      de: 'Ein Glas Wasser, bitte.',
      gloss: { en: 'A glass of water, please.', bg: 'Чаша вода, моля.' },
    },
    tags: ['cafe', 'quantity'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      bg: 'Тук е важна разлика в строежа. Българският казва „чаша вода“ без предлог — и немският прави същото: „ein Glas Wasser“. Никакво von, никакво „от“. Двата езика съвпадат, а английският има „of“.',
      en: 'No "of": German says "ein Glas Wasser", literally "a glass water". Adding von is a common English-speaker mistake.',
    },
  },
  {
    id: 'v-tasse',
    german: 'Tasse',
    display: 'die Tasse',
    article: 'die',
    gender: 'f',
    plural: 'die Tassen',
    wordType: 'noun',
    translation: { en: 'cup', bg: 'чаша (за топло)' },
    pronunciation: { en: 'TAH-se', bg: 'ТА-се' },
    example: {
      de: 'Eine Tasse Kaffee, bitte.',
      gloss: { en: 'A cup of coffee, please.', bg: 'Чаша кафе, моля.' },
    },
    tags: ['cafe', 'quantity'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-glas'],
    notes: {
      bg: 'Немският разделя това, което българският нарича с една дума: Tasse е чаша за топли напитки, Glas е стъклена чаша за студени.',
    },
  },
  {
    id: 'v-teuer',
    german: 'teuer',
    display: 'teuer',
    wordType: 'adjective',
    translation: { en: 'expensive', bg: 'скъп' },
    pronunciation: { en: 'TOY-er', bg: 'ТОЙ-ер' },
    example: {
      de: 'Das ist zu teuer.',
      gloss: { en: 'That is too expensive.', bg: 'Това е твърде скъпо.' },
    },
    tags: ['adjective', 'money'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-billig'],
  },
  {
    id: 'v-billig',
    german: 'billig',
    display: 'billig',
    wordType: 'adjective',
    translation: { en: 'cheap', bg: 'евтин' },
    pronunciation: { en: 'BIL-likh', bg: 'БИ-лих' },
    example: {
      de: 'Der Kaffee ist billig.',
      gloss: { en: 'The coffee is cheap.', bg: 'Кафето е евтино.' },
    },
    tags: ['adjective', 'money'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-teuer'],
  },
  {
    id: 'v-zusammen-getrennt',
    german: 'zusammen oder getrennt',
    display: 'zusammen oder getrennt?',
    wordType: 'phrase',
    translation: { en: 'together or separately?', bg: 'заедно или поотделно?' },
    pronunciation: { en: 'tsoo-ZAH-men OH-der ge-TRENT', bg: 'цу-ЗА-мен О-дер ге-ТРЕНТ' },
    example: {
      de: 'Zusammen oder getrennt?',
      gloss: { en: 'Together or separately?', bg: 'Заедно или поотделно?' },
    },
    tags: ['cafe', 'phrase'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'The question every German waiter asks when you pay in a group. Worth recognising instantly, because you will hear it before you expect it.',
      bg: 'Въпросът, който всеки немски сервитьор задава, когато плащате на група. Струва си да го разпознаваш веднага, защото ще го чуеш по-рано, отколкото очакваш.',
    },
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 3 — shopping and quantities
 * ------------------------------------------------------------------ */

const SHOPPING: VocabEntry[] = [
  {
    id: 'v-supermarkt',
    german: 'Supermarkt',
    display: 'der Supermarkt',
    article: 'der',
    gender: 'm',
    plural: 'die Supermärkte',
    wordType: 'noun',
    translation: { en: 'supermarket', bg: 'супермаркет' },
    pronunciation: { en: 'ZOO-per-markt', bg: 'ЗУ-пер-маркт' },
    example: {
      de: 'Ich gehe in den Supermarkt.',
      gloss: { en: 'I am going to the supermarket.', bg: 'Отивам в супермаркета.' },
    },
    tags: ['shopping'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-kilo',
    german: 'Kilo',
    display: 'das Kilo',
    article: 'das',
    gender: 'n',
    plural: 'die Kilos',
    wordType: 'noun',
    translation: { en: 'kilo', bg: 'килограм' },
    pronunciation: { en: 'KEE-lo', bg: 'КИ-ло' },
    example: {
      de: 'Ein Kilo Äpfel, bitte.',
      gloss: { en: 'A kilo of apples, please.', bg: 'Един килограм ябълки, моля.' },
    },
    tags: ['shopping', 'quantity'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
    notes: {
      en: 'After a quantity the second noun takes no article and no "of": ein Kilo Äpfel, zwei Kilo Tomaten.',
      bg: 'След количество второто съществително няма член и няма предлог: ein Kilo Äpfel. Точно както българското „килограм ябълки“.',
    },
  },
  {
    id: 'v-flasche',
    german: 'Flasche',
    display: 'die Flasche',
    article: 'die',
    gender: 'f',
    plural: 'die Flaschen',
    wordType: 'noun',
    translation: { en: 'bottle', bg: 'бутилка' },
    pronunciation: { en: 'FLA-she', bg: 'ФЛА-ше' },
    example: {
      de: 'Eine Flasche Wasser, bitte.',
      gloss: { en: 'A bottle of water, please.', bg: 'Една бутилка вода, моля.' },
    },
    tags: ['shopping', 'quantity'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-stueck',
    german: 'Stück',
    display: 'das Stück',
    article: 'das',
    gender: 'n',
    plural: 'die Stücke',
    wordType: 'noun',
    translation: { en: 'piece', bg: 'парче, брой' },
    pronunciation: { en: 'shtuek', bg: 'щюк' },
    example: {
      de: 'Ein Stück Kuchen, bitte.',
      gloss: { en: 'A piece of cake, please.', bg: 'Едно парче сладкиш, моля.' },
    },
    tags: ['shopping', 'quantity'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
  },
  {
    id: 'v-kaufen',
    german: 'kaufen',
    display: 'kaufen',
    wordType: 'verb',
    translation: { en: 'to buy', bg: 'купувам' },
    pronunciation: { en: 'KOW-fen', bg: 'КАУ-фен' },
    example: {
      de: 'Ich kaufe einen Apfel.',
      gloss: { en: 'I am buying an apple.', bg: 'Купувам една ябълка.' },
    },
    tags: ['verb', 'shopping', 'accusative'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    related: ['v-einkaufen'],
    notes: {
      en: 'kaufen buys a thing; einkaufen, which you met in Unit 2, is doing the shopping in general. "Ich kaufe Brot" but "Ich kaufe am Samstag ein".',
      bg: 'kaufen купува конкретно нещо; einkaufen, което срещна в раздел 2, е пазаруването изобщо. „Ich kaufe Brot“, но „Ich kaufe am Samstag ein“.',
    },
  },
  {
    id: 'v-brauchen-wir',
    german: 'Was brauchen wir?',
    display: 'Was brauchen wir?',
    wordType: 'phrase',
    translation: { en: 'What do we need?', bg: 'Какво ни трябва?' },
    pronunciation: { en: 'vas BROW-khen veer', bg: 'вас БРАУ-хен вир' },
    example: {
      de: 'Was brauchen wir für heute Abend?',
      gloss: { en: 'What do we need for tonight?', bg: 'Какво ни трябва за тази вечер?' },
    },
    tags: ['shopping', 'phrase'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-noch',
    german: 'noch',
    display: 'noch',
    wordType: 'adverb',
    translation: { en: 'still, another', bg: 'още' },
    pronunciation: { en: 'nokh', bg: 'нох' },
    example: {
      de: 'Noch einen Kaffee, bitte.',
      gloss: { en: 'Another coffee, please.', bg: 'Още едно кафе, моля.' },
    },
    tags: ['adverb'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
    notes: {
      en: '"Noch einen Kaffee" is how you ask for another one — literally "still a coffee". Short, and you will use it constantly.',
      bg: '„Noch einen Kaffee“ е начинът да поискаш още едно — буквално „още едно кафе“. Кратко и ще го използваш постоянно.',
    },
  },
  {
    id: 'v-gern',
    german: 'gern',
    display: 'gern',
    wordType: 'adverb',
    translation: { en: 'gladly, like doing', bg: 'с удоволствие, обичам да' },
    pronunciation: { en: 'gern', bg: 'герн' },
    example: {
      de: 'Ich trinke gern Kaffee.',
      gloss: { en: 'I like drinking coffee.', bg: 'Обичам да пия кафе.' },
    },
    tags: ['adverb'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 4,
    notes: {
      en: 'German has no separate verb for "to like doing something": it adds gern to the verb. "Ich trinke gern Kaffee" is "I like drinking coffee".',
      bg: 'Немският няма отделен глагол за „обичам да правя нещо“: добавя gern към глагола. „Ich trinke gern Kaffee“ значи „Обичам да пия кафе“. Това е много немски начин на изразяване и си струва усилието.',
    },
  },
];

export const FOOD_VOCAB: VocabEntry[] = [...FOOD, ...CAFE, ...SHOPPING];
