import type { VocabEntry } from '../types.ts';

/**
 * Appointments, health and weather (A1 Unit 6).
 *
 * The last A1 unit, and it is chosen to close two gaps rather than open new
 * ground. It extends the dative to a third preposition — bei, as in beim Arzt —
 * so that Unit 5's rule gets one more repetition in a different setting. And it
 * introduces the impersonal `es`, which is the sharpest single contrast with
 * Bulgarian in the whole level: „Вали.“ is a complete Bulgarian sentence with
 * no subject at all, and "Es regnet." cannot lose its es.
 *
 * The health vocabulary is the compound-noun rule paying off: once a learner
 * knows Kopf, Hals and Bauch, the words for the pains build themselves.
 */

const U = 'a1-u6';
const L1 = 'a1-u6-l1';
const L2 = 'a1-u6-l2';
const L3 = 'a1-u6-l3';

/* ------------------------------------------------------------------ *
 * Lesson 1 — appointments
 * ------------------------------------------------------------------ */

const APPOINTMENTS: VocabEntry[] = [
  {
    id: 'v-termin',
    german: 'Termin',
    display: 'der Termin',
    article: 'der',
    gender: 'm',
    plural: 'die Termine',
    wordType: 'noun',
    translation: { en: 'appointment', bg: 'час, среща (уговорена)' },
    pronunciation: { en: 'ter-MEEN', bg: 'тер-МИН' },
    example: {
      de: 'Ich möchte einen Termin.',
      gloss: { en: 'I would like an appointment.', bg: 'Бих искал час.' },
    },
    tags: ['appointment'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      en: 'A Termin is a fixed appointment, not a casual meeting. German life runs on them, and "Ich habe einen Termin" is a complete and respected excuse.',
      bg: 'Termin е записан час, не случайна среща. Немският живот върви по тях и „Ich habe einen Termin“ е пълноценно и уважавано извинение.',
    },
  },
  {
    id: 'v-praxis',
    german: 'Praxis',
    display: 'die Praxis',
    article: 'die',
    gender: 'f',
    plural: 'die Praxen',
    wordType: 'noun',
    translation: { en: 'doctor’s surgery, practice', bg: 'кабинет, практика' },
    pronunciation: { en: 'PRAHK-sis', bg: 'ПРАК-сис' },
    example: {
      de: 'Die Praxis ist heute zu.',
      gloss: { en: 'The surgery is closed today.', bg: 'Кабинетът е затворен днес.' },
    },
    tags: ['appointment', 'health'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      en: 'An irregular plural worth noticing: die Praxen.',
      bg: 'Неправилно множествено число, което си струва да се забележи: die Praxen.',
    },
  },
  {
    id: 'v-bei',
    german: 'bei',
    display: 'bei',
    wordType: 'preposition',
    translation: { en: 'at (a person or place)', bg: 'при' },
    pronunciation: { en: 'by', bg: 'бай' },
    example: {
      de: 'Ich bin beim Arzt.',
      gloss: { en: 'I am at the doctor’s.', bg: 'При лекаря съм.' },
    },
    tags: ['preposition', 'dative'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 4,
    related: ['v-mit', 'v-zu-prep'],
    notes: {
      en: 'The third preposition that always takes the dative, and it contracts the same way: bei dem becomes beim.',
      bg: 'Третият предлог, който винаги взима дателен падеж, и се слива по същия начин: bei dem става beim.',
    },
  },
  {
    id: 'v-absagen',
    german: 'absagen',
    display: 'absagen',
    wordType: 'verb',
    translation: { en: 'to cancel', bg: 'отменям, отказвам' },
    pronunciation: { en: 'AHP-zah-gen', bg: 'АП-за-ген' },
    example: {
      de: 'Ich sage den Termin ab.',
      gloss: { en: 'I am cancelling the appointment.', bg: 'Отменям часа.' },
    },
    tags: ['verb', 'separable', 'appointment'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 4,
    notes: {
      en: 'Separable, so the ab goes to the end: "Ich sage den Termin ab." The same bracket you built in Unit 2.',
      bg: 'Делим, затова ab отива в края: „Ich sage den Termin ab“. Същата рамка, която построи в раздел 2.',
    },
  },
  {
    id: 'v-passt',
    german: 'Das passt',
    display: 'Das passt.',
    wordType: 'phrase',
    translation: { en: 'That works, that suits me', bg: 'Става, удобно ми е' },
    pronunciation: { en: 'das PAST', bg: 'дас ПАСТ' },
    example: {
      de: 'Montag um zehn? Das passt.',
      gloss: { en: 'Monday at ten? That works.', bg: 'Понеделник в десет? Става.' },
    },
    tags: ['appointment', 'phrase'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'The normal way to accept a proposed time. "Das passt mir" is the fuller version.',
      bg: 'Обичайният начин да приемеш предложен час. „Das passt mir“ е по-пълната форма.',
    },
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 2 — health
 * ------------------------------------------------------------------ */

const HEALTH: VocabEntry[] = [
  {
    id: 'v-krank',
    german: 'krank',
    display: 'krank',
    wordType: 'adjective',
    translation: { en: 'ill, sick', bg: 'болен' },
    pronunciation: { en: 'krahnk', bg: 'кранк' },
    example: {
      de: 'Ich bin krank.',
      gloss: { en: 'I am ill.', bg: 'Болен съм.' },
    },
    tags: ['health', 'adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 1,
    related: ['v-gesund'],
  },
  {
    id: 'v-gesund',
    german: 'gesund',
    display: 'gesund',
    wordType: 'adjective',
    translation: { en: 'healthy, well', bg: 'здрав' },
    pronunciation: { en: 'ge-ZOONT', bg: 'ге-ЗУНТ' },
    example: {
      de: 'Ich bin wieder gesund.',
      gloss: { en: 'I am well again.', bg: 'Отново съм здрав.' },
    },
    tags: ['health', 'adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-krank'],
  },
  {
    id: 'v-kopf',
    german: 'Kopf',
    display: 'der Kopf',
    article: 'der',
    gender: 'm',
    plural: 'die Köpfe',
    wordType: 'noun',
    translation: { en: 'head', bg: 'глава' },
    pronunciation: { en: 'kopf', bg: 'копф' },
    example: {
      de: 'Mein Kopf tut weh.',
      gloss: { en: 'My head hurts.', bg: 'Боли ме главата.' },
    },
    tags: ['health', 'body'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
  },
  {
    id: 'v-hals',
    german: 'Hals',
    display: 'der Hals',
    article: 'der',
    gender: 'm',
    plural: 'die Hälse',
    wordType: 'noun',
    translation: { en: 'throat, neck', bg: 'гърло, врат' },
    pronunciation: { en: 'hals', bg: 'халс' },
    example: {
      de: 'Mein Hals tut weh.',
      gloss: { en: 'My throat hurts.', bg: 'Боли ме гърлото.' },
    },
    tags: ['health', 'body'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      bg: 'Една немска дума за две български: Hals покрива и „гърло“, и „врат“.',
      en: 'One word for both throat and neck.',
    },
  },
  {
    id: 'v-bauch',
    german: 'Bauch',
    display: 'der Bauch',
    article: 'der',
    gender: 'm',
    plural: 'die Bäuche',
    wordType: 'noun',
    translation: { en: 'stomach, belly', bg: 'корем' },
    pronunciation: { en: 'bowkh', bg: 'баух' },
    example: {
      de: 'Mein Bauch tut weh.',
      gloss: { en: 'My stomach hurts.', bg: 'Боли ме коремът.' },
    },
    tags: ['health', 'body'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
  },
  {
    id: 'v-schmerzen',
    german: 'Schmerzen',
    display: 'die Schmerzen',
    article: 'die',
    gender: 'f',
    plural: 'die Schmerzen',
    wordType: 'noun',
    translation: { en: 'pain, aches', bg: 'болки' },
    pronunciation: { en: 'SHMER-tsen', bg: 'ШМЕР-цен' },
    example: {
      de: 'Ich habe Kopfschmerzen.',
      gloss: { en: 'I have a headache.', bg: 'Боли ме главата.' },
    },
    tags: ['health'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'Used in the plural and stuck onto the body part: Kopfschmerzen, Halsschmerzen, Bauchschmerzen. Learn the pattern, not the three words.',
      bg: 'Използва се в множествено число и се залепва за частта от тялото: Kopfschmerzen, Halsschmerzen, Bauchschmerzen. Научи модела, не трите думи.',
    },
  },
  {
    id: 'v-fieber',
    german: 'Fieber',
    display: 'das Fieber',
    article: 'das',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'fever, temperature', bg: 'температура, треска' },
    pronunciation: { en: 'FEE-ber', bg: 'ФИ-бер' },
    example: {
      de: 'Ich habe Fieber.',
      gloss: { en: 'I have a temperature.', bg: 'Имам температура.' },
    },
    tags: ['health'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'No article when you say you have it: "Ich habe Fieber", the same way as "Ich habe Hunger".',
      bg: 'Без член, когато казваш, че я имаш: „Ich habe Fieber“, също както „Ich habe Hunger“.',
    },
  },
  {
    id: 'v-erkaeltung',
    german: 'Erkältung',
    display: 'die Erkältung',
    article: 'die',
    gender: 'f',
    plural: 'die Erkältungen',
    wordType: 'noun',
    translation: { en: 'cold (illness)', bg: 'настинка' },
    pronunciation: { en: 'er-KEL-toong', bg: 'ер-КЕЛ-тунг' },
    example: {
      de: 'Ich habe eine Erkältung.',
      gloss: { en: 'I have a cold.', bg: 'Имам настинка.' },
    },
    tags: ['health'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'Built from kalt. The illness takes an article — eine Erkältung — while Fieber does not.',
      bg: 'Образувано от kalt. Болестта взима член — eine Erkältung — докато Fieber не взима.',
    },
  },
  {
    id: 'v-weh-tun',
    german: 'weh tun',
    display: 'weh tun',
    wordType: 'phrase',
    translation: { en: 'to hurt', bg: 'боли' },
    pronunciation: { en: 'vay TOON', bg: 'ве ТУН' },
    example: {
      de: 'Mein Kopf tut weh.',
      gloss: { en: 'My head hurts.', bg: 'Боли ме главата.' },
    },
    tags: ['health', 'phrase'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    notes: {
      bg: 'Внимавай със строежа — той е обратен на българския. Българският казва „боли ме главата“, където главата е подлог, а „ме“ е допълнение. Немският казва „Mein Kopf tut weh“ — главата е подлогът и тя „прави боля“. Няма „ме“.',
      en: 'The body part is the subject: "Mein Kopf tut weh" is literally "my head does hurt". weh goes to the end, like a separable verb.',
    },
  },
  {
    id: 'v-gute-besserung',
    german: 'Gute Besserung',
    display: 'Gute Besserung!',
    wordType: 'phrase',
    translation: { en: 'Get well soon', bg: 'Оздравявай' },
    pronunciation: { en: 'GOO-te BES-se-roong', bg: 'ГУ-те БЕ-се-рунг' },
    example: {
      de: 'Gute Besserung!',
      gloss: { en: 'Get well soon!', bg: 'Оздравявай!' },
    },
    tags: ['health', 'phrase'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'What you say to someone who is ill. Not optional politeness in German — its absence is noticed.',
      bg: 'Това, което се казва на болен човек. В немския не е незадължителна учтивост — липсата ѝ се забелязва.',
    },
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 3 — weather
 * ------------------------------------------------------------------ */

const WEATHER: VocabEntry[] = [
  {
    id: 'v-wetter',
    german: 'Wetter',
    display: 'das Wetter',
    article: 'das',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'weather', bg: 'време (метеорологично)' },
    pronunciation: { en: 'VET-ter', bg: 'ВЕ-тер' },
    example: {
      de: 'Wie ist das Wetter?',
      gloss: { en: 'What is the weather like?', bg: 'Какво е времето?' },
    },
    tags: ['weather'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    related: ['v-zeit'],
    notes: {
      bg: 'Тук е разделянето, което българският не прави: „време“ е и Zeit (часовниковото), и Wetter (навън). Немският никога не ги бърка.',
      en: 'Germans ask "Wie ist das Wetter?" — how is the weather — rather than what it is like.',
    },
  },
  {
    id: 'v-regnen',
    german: 'regnen',
    display: 'regnen',
    wordType: 'verb',
    translation: { en: 'to rain', bg: 'вали дъжд' },
    pronunciation: { en: 'RAYG-nen', bg: 'РЕГ-нен' },
    example: {
      de: 'Es regnet.',
      gloss: { en: 'It is raining.', bg: 'Вали.' },
    },
    tags: ['weather', 'verb'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
    notes: {
      bg: 'Тук е най-ясната структурна разлика в цялото ниво. „Вали.“ е цяло българско изречение без подлог. Немското „Es regnet.“ не може да изпусне es — изречението без подлог просто не съществува в немския.',
      en: 'Only ever used with es: es regnet. There is no other subject it can take.',
    },
  },
  {
    id: 'v-schneien',
    german: 'schneien',
    display: 'schneien',
    wordType: 'verb',
    translation: { en: 'to snow', bg: 'вали сняг' },
    pronunciation: { en: 'SHNY-en', bg: 'ШНАЙ-ен' },
    example: {
      de: 'Es schneit.',
      gloss: { en: 'It is snowing.', bg: 'Вали сняг.' },
    },
    tags: ['weather', 'verb'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
  },
  {
    id: 'v-sonne',
    german: 'Sonne',
    display: 'die Sonne',
    article: 'die',
    gender: 'f',
    plural: 'die Sonnen',
    wordType: 'noun',
    translation: { en: 'sun', bg: 'слънце' },
    pronunciation: { en: 'ZON-ne', bg: 'ЗО-не' },
    example: {
      de: 'Die Sonne scheint.',
      gloss: { en: 'The sun is shining.', bg: 'Слънцето грее.' },
    },
    tags: ['weather'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    notes: {
      bg: 'Родовете се разминават: „слънце“ е среден род, а die Sonne е женски. Немският смята слънцето за женско, а луната за мъжка — обратното на повечето европейски езици.',
    },
  },
  {
    id: 'v-scheinen',
    german: 'scheinen',
    display: 'scheinen',
    wordType: 'verb',
    translation: { en: 'to shine', bg: 'грея, светя' },
    pronunciation: { en: 'SHY-nen', bg: 'ШАЙ-нен' },
    example: {
      de: 'Die Sonne scheint heute.',
      gloss: { en: 'The sun is shining today.', bg: 'Слънцето грее днес.' },
    },
    tags: ['weather', 'verb'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
  },
  {
    id: 'v-kalt',
    german: 'kalt',
    display: 'kalt',
    wordType: 'adjective',
    translation: { en: 'cold', bg: 'студено' },
    pronunciation: { en: 'kalt', bg: 'калт' },
    example: {
      de: 'Es ist kalt.',
      gloss: { en: 'It is cold.', bg: 'Студено е.' },
    },
    tags: ['weather', 'adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 1,
    related: ['v-warm'],
  },
  {
    id: 'v-warm',
    german: 'warm',
    display: 'warm',
    wordType: 'adjective',
    translation: { en: 'warm', bg: 'топло' },
    pronunciation: { en: 'varm', bg: 'варм' },
    example: {
      de: 'Heute ist es warm.',
      gloss: { en: 'Today it is warm.', bg: 'Днес е топло.' },
    },
    tags: ['weather', 'adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 1,
    related: ['v-kalt'],
  },
  {
    id: 'v-heiss',
    german: 'heiß',
    display: 'heiß',
    wordType: 'adjective',
    translation: { en: 'hot', bg: 'горещо' },
    pronunciation: { en: 'hyce', bg: 'хайс' },
    example: {
      de: 'Im Sommer ist es heiß.',
      gloss: { en: 'In summer it is hot.', bg: 'През лятото е горещо.' },
    },
    tags: ['weather', 'adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    notes: {
      en: 'Written with ß, and not to be confused with heißen, to be called.',
      bg: 'Пише се с ß и да не се бърка с heißen — „казвам се“.',
    },
  },
  {
    id: 'v-windig',
    german: 'windig',
    display: 'windig',
    wordType: 'adjective',
    translation: { en: 'windy', bg: 'ветровито' },
    pronunciation: { en: 'VIN-dikh', bg: 'ВИН-дих' },
    example: {
      de: 'Es ist windig.',
      gloss: { en: 'It is windy.', bg: 'Ветровито е.' },
    },
    tags: ['weather', 'adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-sommer',
    german: 'Sommer',
    display: 'der Sommer',
    article: 'der',
    gender: 'm',
    plural: 'die Sommer',
    wordType: 'noun',
    translation: { en: 'summer', bg: 'лято' },
    pronunciation: { en: 'ZOM-mer', bg: 'ЗО-мер' },
    example: {
      de: 'Im Sommer schwimme ich oft.',
      gloss: { en: 'In summer I often swim.', bg: 'През лятото плувам често.' },
    },
    tags: ['weather', 'time'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    notes: {
      en: 'Seasons are all masculine, and they take im: im Sommer, im Winter.',
      bg: 'Сезоните са всички от мъжки род и взимат im: im Sommer, im Winter.',
    },
  },
  {
    id: 'v-winter',
    german: 'Winter',
    display: 'der Winter',
    article: 'der',
    gender: 'm',
    plural: 'die Winter',
    wordType: 'noun',
    translation: { en: 'winter', bg: 'зима' },
    pronunciation: { en: 'VIN-ter', bg: 'ВИН-тер' },
    example: {
      de: 'Im Winter schneit es oft.',
      gloss: { en: 'In winter it often snows.', bg: 'През зимата често вали сняг.' },
    },
    tags: ['weather', 'time'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    related: ['v-sommer'],
  },
];

export const HEALTH_VOCAB: VocabEntry[] = [...APPOINTMENTS, ...HEALTH, ...WEATHER];
