import type { VocabEntry } from '../types.ts';

/**
 * Home, daily routine and the first modal verbs (A1 Unit 2).
 *
 * The vocabulary is chosen to serve one structural idea: the German sentence
 * bracket. A separable verb (aufstehen) and a modal verb (müssen) both put
 * something at the *end* of the sentence, and that is the biggest structural
 * departure from both English and Bulgarian at this level. So the verbs here
 * are not a random selection of useful words — they are the ones that force a
 * learner to build the bracket over and over: aufstehen, einkaufen, fernsehen,
 * aufräumen, anfangen.
 *
 * The rooms and furniture serve a second purpose: they are mostly masculine and
 * neuter, which keeps Unit 1's accusative alive every time the learner says what
 * there is in a room.
 */

const U = 'a1-u2';
const L1 = 'a1-u2-l1';
const L2 = 'a1-u2-l2';
const L3 = 'a1-u2-l3';

/* ------------------------------------------------------------------ *
 * Lesson 1 — where you live
 * ------------------------------------------------------------------ */

const HOME: VocabEntry[] = [
  {
    id: 'v-wohnung',
    german: 'Wohnung',
    display: 'die Wohnung',
    article: 'die',
    gender: 'f',
    plural: 'die Wohnungen',
    wordType: 'noun',
    translation: { en: 'flat, apartment', bg: 'апартамент, жилище' },
    pronunciation: { en: 'VOH-noong', bg: 'ВО-нунг' },
    example: {
      de: 'Meine Wohnung ist klein.',
      gloss: { en: 'My flat is small.', bg: 'Апартаментът ми е малък.' },
    },
    tags: ['home'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    related: ['v-wohnen'],
    notes: {
      en: 'Built from wohnen, which you already know: the place where you wohnen is a Wohnung. German does this constantly, and spotting it saves a lot of memorising.',
      bg: 'Образувано от wohnen, което вече знаеш: мястото, където живееш, е Wohnung. Немският прави това постоянно и разпознаването му спестява много зубрене.',
    },
  },
  {
    id: 'v-zimmer',
    german: 'Zimmer',
    display: 'das Zimmer',
    article: 'das',
    gender: 'n',
    plural: 'die Zimmer',
    wordType: 'noun',
    translation: { en: 'room', bg: 'стая' },
    pronunciation: { en: 'TSIM-mer', bg: 'ЦИ-мер' },
    example: {
      de: 'Die Wohnung hat drei Zimmer.',
      gloss: { en: 'The flat has three rooms.', bg: 'Апартаментът има три стаи.' },
    },
    tags: ['home'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Родовете не съвпадат: „стая“ е женски род на български, а das Zimmer е среден на немски. Множественото число е същото като единственото — die Zimmer.',
      en: 'The plural is identical to the singular. Only the article changes: das Zimmer, die Zimmer.',
    },
  },
  {
    id: 'v-kueche',
    german: 'Küche',
    display: 'die Küche',
    article: 'die',
    gender: 'f',
    plural: 'die Küchen',
    wordType: 'noun',
    translation: { en: 'kitchen', bg: 'кухня' },
    pronunciation: { en: 'KUE-khe', bg: 'КЮ-хе' },
    example: {
      de: 'Die Küche ist sehr klein.',
      gloss: { en: 'The kitchen is very small.', bg: 'Кухнята е много малка.' },
    },
    tags: ['home'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'Mind the ü. "Kuchen" without the umlaut is cake, and it is a different word entirely — die Küche, der Kuchen.',
      bg: 'Внимавай с ü. Без умлаут „Kuchen“ значи сладкиш и е съвсем друга дума — die Küche, der Kuchen.',
    },
  },
  {
    id: 'v-bad',
    german: 'Bad',
    display: 'das Bad',
    article: 'das',
    gender: 'n',
    plural: 'die Bäder',
    wordType: 'noun',
    translation: { en: 'bathroom', bg: 'баня' },
    pronunciation: { en: 'baht', bg: 'бат' },
    example: {
      de: 'Das Bad ist neben der Küche.',
      gloss: { en: 'The bathroom is next to the kitchen.', bg: 'Банята е до кухнята.' },
    },
    tags: ['home'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
  },
  {
    id: 'v-schlafzimmer',
    german: 'Schlafzimmer',
    display: 'das Schlafzimmer',
    article: 'das',
    gender: 'n',
    plural: 'die Schlafzimmer',
    wordType: 'noun',
    translation: { en: 'bedroom', bg: 'спалня' },
    pronunciation: { en: 'SHLAHF-tsim-mer', bg: 'ШЛАФ-ци-мер' },
    example: {
      de: 'Mein Schlafzimmer ist klein.',
      gloss: { en: 'My bedroom is small.', bg: 'Спалнята ми е малка.' },
    },
    tags: ['home'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    related: ['v-schlafen', 'v-zimmer'],
    notes: {
      en: 'schlafen + Zimmer: the sleep-room. A compound takes the gender of its last part, so because it is das Zimmer, it is das Schlafzimmer.',
      bg: 'schlafen + Zimmer: стаята за спане. Сложната дума взима рода на последната си част — щом е das Zimmer, значи е das Schlafzimmer. Това правило важи винаги и спестява много.',
    },
  },
  {
    id: 'v-wohnzimmer',
    german: 'Wohnzimmer',
    display: 'das Wohnzimmer',
    article: 'das',
    gender: 'n',
    plural: 'die Wohnzimmer',
    wordType: 'noun',
    translation: { en: 'living room', bg: 'дневна' },
    pronunciation: { en: 'VOHN-tsim-mer', bg: 'ВОН-ци-мер' },
    example: {
      de: 'Wir sind im Wohnzimmer.',
      gloss: { en: 'We are in the living room.', bg: 'В дневната сме.' },
    },
    tags: ['home'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    related: ['v-zimmer'],
  },
  {
    id: 'v-bett',
    german: 'Bett',
    display: 'das Bett',
    article: 'das',
    gender: 'n',
    plural: 'die Betten',
    wordType: 'noun',
    translation: { en: 'bed', bg: 'легло' },
    pronunciation: { en: 'bet', bg: 'бет' },
    example: {
      de: 'Das Bett ist neu.',
      gloss: { en: 'The bed is new.', bg: 'Леглото е ново.' },
    },
    tags: ['home', 'furniture'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-stuhl',
    german: 'Stuhl',
    display: 'der Stuhl',
    article: 'der',
    gender: 'm',
    plural: 'die Stühle',
    wordType: 'noun',
    translation: { en: 'chair', bg: 'стол' },
    pronunciation: { en: 'shtool', bg: 'щул' },
    example: {
      de: 'Ich brauche einen Stuhl.',
      gloss: { en: 'I need a chair.', bg: 'Трябва ми стол.' },
    },
    tags: ['home', 'furniture'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'Masculine, so it is the one that changes as an object: einen Stuhl, keinen Stuhl.',
      bg: 'Мъжки род, значи това е думата, която се мени като допълнение: einen Stuhl, keinen Stuhl.',
    },
  },
  {
    id: 'v-schrank',
    german: 'Schrank',
    display: 'der Schrank',
    article: 'der',
    gender: 'm',
    plural: 'die Schränke',
    wordType: 'noun',
    translation: { en: 'cupboard, wardrobe', bg: 'шкаф, гардероб' },
    pronunciation: { en: 'shrahnk', bg: 'шранк' },
    example: {
      de: 'Der Schrank ist groß.',
      gloss: { en: 'The wardrobe is big.', bg: 'Гардеробът е голям.' },
    },
    tags: ['home', 'furniture'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
  },
  {
    id: 'v-fenster',
    german: 'Fenster',
    display: 'das Fenster',
    article: 'das',
    gender: 'n',
    plural: 'die Fenster',
    wordType: 'noun',
    translation: { en: 'window', bg: 'прозорец' },
    pronunciation: { en: 'FENS-ter', bg: 'ФЕНС-тер' },
    example: {
      de: 'Das Zimmer hat zwei Fenster.',
      gloss: { en: 'The room has two windows.', bg: 'Стаята има два прозореца.' },
    },
    tags: ['home'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Пак разминаване: „прозорец“ е мъжки род, а das Fenster е среден. Множественото число е същото като единственото.',
    },
  },
  {
    id: 'v-tuer',
    german: 'Tür',
    display: 'die Tür',
    article: 'die',
    gender: 'f',
    plural: 'die Türen',
    wordType: 'noun',
    translation: { en: 'door', bg: 'врата' },
    pronunciation: { en: 'tuer', bg: 'тюр' },
    example: {
      de: 'Die Tür ist offen.',
      gloss: { en: 'The door is open.', bg: 'Вратата е отворена.' },
    },
    tags: ['home'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
  },
  {
    id: 'v-garten',
    german: 'Garten',
    display: 'der Garten',
    article: 'der',
    gender: 'm',
    plural: 'die Gärten',
    wordType: 'noun',
    translation: { en: 'garden', bg: 'градина' },
    pronunciation: { en: 'GAR-ten', bg: 'ГАР-тен' },
    example: {
      de: 'Wir haben einen Garten.',
      gloss: { en: 'We have a garden.', bg: 'Имаме градина.' },
    },
    tags: ['home'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
  },
  {
    id: 'v-gross',
    german: 'groß',
    display: 'groß',
    wordType: 'adjective',
    translation: { en: 'big, tall', bg: 'голям, висок' },
    pronunciation: { en: 'grohs', bg: 'грос' },
    example: {
      de: 'Das Haus ist sehr groß.',
      gloss: { en: 'The house is very big.', bg: 'Къщата е много голяма.' },
    },
    tags: ['adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
    related: ['v-klein'],
    notes: {
      en: 'Written with ß. It also means "tall" about a person: "Mein Bruder ist groß."',
      bg: 'Пише се с ß. Използва се и за човек в смисъл „висок“: „Mein Bruder ist groß“.',
    },
  },
  {
    id: 'v-klein',
    german: 'klein',
    display: 'klein',
    wordType: 'adjective',
    translation: { en: 'small, short', bg: 'малък, нисък' },
    pronunciation: { en: 'klyne', bg: 'клайн' },
    example: {
      de: 'Meine Küche ist klein.',
      gloss: { en: 'My kitchen is small.', bg: 'Кухнята ми е малка.' },
    },
    tags: ['adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
    related: ['v-gross'],
  },
  {
    id: 'v-neu',
    german: 'neu',
    display: 'neu',
    wordType: 'adjective',
    translation: { en: 'new', bg: 'нов' },
    pronunciation: { en: 'noy', bg: 'ной' },
    example: {
      de: 'Der Schrank ist neu.',
      gloss: { en: 'The wardrobe is new.', bg: 'Гардеробът е нов.' },
    },
    tags: ['adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
    notes: {
      en: 'eu is pronounced "oy", the same sound as in Freund and Deutsch.',
      bg: 'eu се чете „ой“ — същият звук като във Freund и Deutsch.',
    },
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 2 — the day, and separable verbs
 * ------------------------------------------------------------------ */

const ROUTINE: VocabEntry[] = [
  {
    id: 'v-aufstehen',
    german: 'aufstehen',
    display: 'aufstehen',
    wordType: 'verb',
    translation: { en: 'to get up', bg: 'ставам (от сън)' },
    pronunciation: { en: 'OWF-shtay-en', bg: 'АУФ-щее-ен' },
    example: {
      de: 'Ich stehe um sieben Uhr auf.',
      gloss: { en: 'I get up at seven o’clock.', bg: 'Ставам в седем часа.' },
    },
    tags: ['verb', 'separable', 'routine'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    notes: {
      en: 'A separable verb: in a normal sentence the auf breaks off and goes to the very end. "Ich stehe auf", never "Ich aufstehe".',
      bg: 'Делим глагол: в обикновено изречение auf се отделя и отива най-накрая. „Ich stehe auf“, никога „Ich aufstehe“.',
    },
  },
  {
    id: 'v-einkaufen',
    german: 'einkaufen',
    display: 'einkaufen',
    wordType: 'verb',
    translation: { en: 'to shop, to do the shopping', bg: 'пазарувам' },
    pronunciation: { en: 'EYEN-kow-fen', bg: 'АЙН-кау-фен' },
    example: {
      de: 'Ich kaufe am Samstag ein.',
      gloss: { en: 'I do the shopping on Saturday.', bg: 'Пазарувам в събота.' },
    },
    tags: ['verb', 'separable', 'routine'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
  },
  {
    id: 'v-fernsehen',
    german: 'fernsehen',
    display: 'fernsehen',
    wordType: 'verb',
    translation: { en: 'to watch television', bg: 'гледам телевизия' },
    pronunciation: { en: 'FERN-zay-en', bg: 'ФЕРН-зее-ен' },
    example: {
      de: 'Am Abend sehe ich fern.',
      gloss: { en: 'In the evening I watch television.', bg: 'Вечер гледам телевизия.' },
    },
    tags: ['verb', 'separable', 'routine'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    notes: {
      en: 'fern means "far" and sehen means "to see": far-seeing. One word does the whole job, so there is no object to add.',
      bg: 'fern значи „далече“, sehen значи „виждам“: далекогледане. Една дума върши цялата работа — не се добавя допълнение.',
    },
  },
  {
    id: 'v-aufraeumen',
    german: 'aufräumen',
    display: 'aufräumen',
    wordType: 'verb',
    translation: { en: 'to tidy up', bg: 'разтребвам' },
    pronunciation: { en: 'OWF-roy-men', bg: 'АУФ-рой-мен' },
    example: {
      de: 'Ich räume mein Zimmer auf.',
      gloss: { en: 'I tidy up my room.', bg: 'Разтребвам стаята си.' },
    },
    tags: ['verb', 'separable', 'routine'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    notes: {
      bg: 'Забележи къде отива допълнението: „Ich räume mein Zimmer auf“ — mein Zimmer стои между двете части на глагола. Точно това е немската рамка.',
    },
  },
  {
    id: 'v-anfangen',
    german: 'anfangen',
    display: 'anfangen',
    wordType: 'verb',
    translation: { en: 'to start, to begin', bg: 'започвам' },
    pronunciation: { en: 'AHN-fahng-en', bg: 'АН-фанг-ен' },
    example: {
      de: 'Die Arbeit fängt um acht Uhr an.',
      gloss: { en: 'Work starts at eight o’clock.', bg: 'Работата започва в осем часа.' },
    },
    tags: ['verb', 'separable', 'routine'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 5,
    notes: {
      en: 'Separable and irregular: the a becomes ä in the du and er forms — du fängst an, er fängt an.',
      bg: 'Делим и неправилен: a става ä при du и er — du fängst an, er fängt an.',
    },
  },
  {
    id: 'v-schlafen',
    german: 'schlafen',
    display: 'schlafen',
    wordType: 'verb',
    translation: { en: 'to sleep', bg: 'спя' },
    pronunciation: { en: 'SHLAH-fen', bg: 'ШЛА-фен' },
    example: {
      de: 'Das Baby schläft.',
      gloss: { en: 'The baby is sleeping.', bg: 'Бебето спи.' },
    },
    tags: ['verb', 'routine', 'irregular'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'Irregular: du schläfst, er schläft. The a takes an umlaut.',
      bg: 'Неправилен: du schläfst, er schläft. Гласната a взима умлаут.',
    },
  },
  {
    id: 'v-essen',
    german: 'essen',
    display: 'essen',
    wordType: 'verb',
    translation: { en: 'to eat', bg: 'ям' },
    pronunciation: { en: 'ES-sen', bg: 'Е-сен' },
    example: {
      de: 'Wir essen um eins.',
      gloss: { en: 'We eat at one.', bg: 'Ядем в един.' },
    },
    tags: ['verb', 'routine', 'irregular'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'Irregular: du isst, er isst. Both forms look the same, which is unusual and worth noticing.',
      bg: 'Неправилен: du isst, er isst. Двете форми изглеждат еднакво — рядкост, която си струва да се забележи.',
    },
  },
  {
    id: 'v-trinken',
    german: 'trinken',
    display: 'trinken',
    wordType: 'verb',
    translation: { en: 'to drink', bg: 'пия' },
    pronunciation: { en: 'TRING-ken', bg: 'ТРИН-кен' },
    example: {
      de: 'Ich trinke Wasser.',
      gloss: { en: 'I drink water.', bg: 'Пия вода.' },
    },
    tags: ['verb', 'routine'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
  },
  {
    id: 'v-kochen',
    german: 'kochen',
    display: 'kochen',
    wordType: 'verb',
    translation: { en: 'to cook', bg: 'готвя' },
    pronunciation: { en: 'KO-khen', bg: 'КО-хен' },
    example: {
      de: 'Mein Vater kocht sehr gut.',
      gloss: { en: 'My father cooks very well.', bg: 'Баща ми готви много добре.' },
    },
    tags: ['verb', 'routine'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
  },
  {
    id: 'v-fruehstueck',
    german: 'Frühstück',
    display: 'das Frühstück',
    article: 'das',
    gender: 'n',
    plural: 'die Frühstücke',
    wordType: 'noun',
    translation: { en: 'breakfast', bg: 'закуска' },
    pronunciation: { en: 'FRUE-shtuek', bg: 'ФРЮ-щюк' },
    example: {
      de: 'Das Frühstück ist um acht.',
      gloss: { en: 'Breakfast is at eight.', bg: 'Закуската е в осем.' },
    },
    tags: ['routine', 'food'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'früh (early) plus Stück (piece): the early piece. Two umlauts in one word — worth typing slowly.',
      bg: 'früh (рано) плюс Stück (парче): ранното парче. Два умлаута в една дума — струва си да се напише бавно.',
    },
  },
  {
    // Taught as the whole phrase rather than as the bare noun, and not only for
    // convenience: `morgen` (tomorrow) is already in the course, and the word
    // lookup is case-insensitive, so a second entry spelt Morgen would quietly
    // shadow it. The phrase is also what a learner actually needs to say.
    id: 'v-am-morgen',
    german: 'am Morgen',
    display: 'am Morgen',
    wordType: 'phrase',
    translation: { en: 'in the morning', bg: 'сутрин' },
    pronunciation: { en: 'am MOR-gen', bg: 'ам МОР-ген' },
    example: {
      de: 'Am Morgen trinke ich Wasser.',
      gloss: { en: 'In the morning I drink water.', bg: 'Сутрин пия вода.' },
    },
    tags: ['time', 'phrase'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'Careful: "morgen" in lower case means tomorrow, while "der Morgen" with a capital is the morning. The capital letter is the whole difference — "morgen Morgen" is a real thing to say.',
      bg: 'Внимавай: „morgen“ с малка буква значи „утре“, а „der Morgen“ с главна е „сутрин“. Главната буква е цялата разлика — „morgen Morgen“ наистина се казва.',
    },
  },
  {
    id: 'v-abend',
    german: 'Abend',
    display: 'der Abend',
    article: 'der',
    gender: 'm',
    plural: 'die Abende',
    wordType: 'noun',
    translation: { en: 'evening', bg: 'вечер' },
    pronunciation: { en: 'AH-bent', bg: 'А-бент' },
    example: {
      de: 'Am Abend sehe ich fern.',
      gloss: { en: 'In the evening I watch television.', bg: 'Вечер гледам телевизия.' },
    },
    tags: ['time'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      bg: 'Родовете се разминават: „вечер“ е женски род на български, а der Abend е мъжки на немски.',
    },
  },
  {
    id: 'v-immer',
    german: 'immer',
    display: 'immer',
    wordType: 'adverb',
    translation: { en: 'always', bg: 'винаги' },
    pronunciation: { en: 'IM-mer', bg: 'И-мер' },
    example: {
      de: 'Ich stehe immer früh auf.',
      gloss: { en: 'I always get up early.', bg: 'Винаги ставам рано.' },
    },
    tags: ['adverb', 'frequency'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
  },
  {
    id: 'v-oft',
    german: 'oft',
    display: 'oft',
    wordType: 'adverb',
    translation: { en: 'often', bg: 'често' },
    pronunciation: { en: 'oft', bg: 'офт' },
    example: {
      de: 'Wir kochen oft zusammen.',
      gloss: { en: 'We often cook together.', bg: 'Често готвим заедно.' },
    },
    tags: ['adverb', 'frequency'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 1,
  },
  {
    id: 'v-manchmal',
    german: 'manchmal',
    display: 'manchmal',
    wordType: 'adverb',
    translation: { en: 'sometimes', bg: 'понякога' },
    pronunciation: { en: 'MANKH-mahl', bg: 'МАНХ-мал' },
    example: {
      de: 'Manchmal esse ich nicht.',
      gloss: { en: 'Sometimes I do not eat.', bg: 'Понякога не ям.' },
    },
    tags: ['adverb', 'frequency'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
  },
  {
    id: 'v-nie',
    german: 'nie',
    display: 'nie',
    wordType: 'adverb',
    translation: { en: 'never', bg: 'никога' },
    pronunciation: { en: 'nee', bg: 'ни' },
    example: {
      de: 'Ich sehe nie fern.',
      gloss: { en: 'I never watch television.', bg: 'Никога не гледам телевизия.' },
    },
    tags: ['adverb', 'frequency'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      bg: 'Важна разлика. Българският използва двойно отрицание: „никога не гледам“. Немският използва само едно: „Ich sehe nie fern“ — без nicht. Добавянето на nicht тук е грешка.',
      en: 'One negative is enough: "Ich sehe nie fern", not "Ich sehe nie nicht fern".',
    },
  },
  {
    id: 'v-frueh',
    german: 'früh',
    display: 'früh',
    wordType: 'adverb',
    translation: { en: 'early', bg: 'рано' },
    pronunciation: { en: 'frue', bg: 'фрю' },
    example: {
      de: 'Ich stehe früh auf.',
      gloss: { en: 'I get up early.', bg: 'Ставам рано.' },
    },
    tags: ['adverb', 'time'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-spaet'],
  },
  {
    id: 'v-spaet',
    german: 'spät',
    display: 'spät',
    wordType: 'adverb',
    translation: { en: 'late', bg: 'късно' },
    pronunciation: { en: 'shpayt', bg: 'щпет' },
    example: {
      de: 'Am Wochenende stehe ich spät auf.',
      gloss: { en: 'At the weekend I get up late.', bg: 'През уикенда ставам късно.' },
    },
    tags: ['adverb', 'time'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-frueh'],
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 3 — modal verbs
 * ------------------------------------------------------------------ */

const MODALS: VocabEntry[] = [
  {
    id: 'v-koennen',
    german: 'können',
    display: 'können',
    wordType: 'verb',
    translation: { en: 'can, to be able to', bg: 'мога' },
    pronunciation: { en: 'KOEN-nen', bg: 'КЬО-нен' },
    example: {
      de: 'Ich kann gut kochen.',
      gloss: { en: 'I can cook well.', bg: 'Мога да готвя добре.' },
    },
    tags: ['verb', 'modal'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 4,
    notes: {
      en: 'The ich and er forms are the same and have no ending: ich kann, er kann. That is true of every modal verb.',
      bg: 'Формите за ich и er са еднакви и без окончание: ich kann, er kann. Това важи за всички модални глаголи.',
    },
  },
  {
    id: 'v-muessen',
    german: 'müssen',
    display: 'müssen',
    wordType: 'verb',
    translation: { en: 'must, to have to', bg: 'трябва' },
    pronunciation: { en: 'MUES-sen', bg: 'МЮ-сен' },
    example: {
      de: 'Ich muss heute arbeiten.',
      gloss: { en: 'I have to work today.', bg: 'Днес трябва да работя.' },
    },
    tags: ['verb', 'modal'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 4,
    notes: {
      bg: 'Голяма разлика в строежа. Българското „трябва“ е безлично: „трябва да работя“. Немското müssen се спряга по лицето: ich muss, du musst, er muss. И вторият глагол отива най-накрая, без „да“.',
      en: 'ich muss, du musst, er muss — no -t on the er form, which looks wrong and is right.',
    },
  },
  {
    id: 'v-wollen',
    german: 'wollen',
    display: 'wollen',
    wordType: 'verb',
    translation: { en: 'to want to', bg: 'искам' },
    pronunciation: { en: 'VOL-len', bg: 'ВО-лен' },
    example: {
      de: 'Wir wollen heute einkaufen.',
      gloss: { en: 'We want to go shopping today.', bg: 'Днес искаме да пазаруваме.' },
    },
    tags: ['verb', 'modal'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 4,
    notes: {
      en: 'ich will does not mean "I will" — it means "I want". A false friend worth remembering early.',
      bg: '„ich will“ не значи „ще“, а „искам“. Подвеждаща прилика с английското will, която е добре да се запомни рано.',
    },
  },
  {
    id: 'v-arbeit',
    german: 'Arbeit',
    display: 'die Arbeit',
    article: 'die',
    gender: 'f',
    plural: 'die Arbeiten',
    wordType: 'noun',
    translation: { en: 'work, job', bg: 'работа' },
    pronunciation: { en: 'AR-byte', bg: 'АР-байт' },
    example: {
      de: 'Die Arbeit fängt um acht an.',
      gloss: { en: 'Work starts at eight.', bg: 'Работата започва в осем.' },
    },
    tags: ['work'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    related: ['v-arbeiten'],
  },
  {
    id: 'v-heute-abend',
    german: 'heute Abend',
    display: 'heute Abend',
    wordType: 'phrase',
    translation: { en: 'this evening, tonight', bg: 'тази вечер' },
    pronunciation: { en: 'HOY-te AH-bent', bg: 'ХОЙ-те А-бент' },
    example: {
      de: 'Heute Abend will ich fernsehen.',
      gloss: { en: 'Tonight I want to watch television.', bg: 'Тази вечер искам да гледам телевизия.' },
    },
    tags: ['time', 'phrase'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    notes: {
      en: 'Two words, no preposition: not "am heute Abend". The same pattern gives heute Morgen and morgen Abend.',
      bg: 'Две думи, без предлог: не „am heute Abend“. Същият модел дава heute Morgen и morgen Abend.',
    },
  },
];

export const HOME_VOCAB: VocabEntry[] = [...HOME, ...ROUTINE, ...MODALS];
