import type { VocabEntry } from '../types.ts';

/**
 * Countries, languages, nationalities, occupations and family (Pre-A1 Unit 4).
 *
 * Two things carry most of the pedagogical weight here, and both get notes:
 * German drops the article in front of a profession ("Ich bin Lehrerin"), and
 * nationalities and professions have a feminine form in -in that is not
 * optional when you are talking about a woman.
 */

const U = 'pre-a1-u4';
const L1 = 'pre-a1-u4-l1';
const L2 = 'pre-a1-u4-l2';
const L3 = 'pre-a1-u4-l3';

const COUNTRIES_AND_LANGUAGES: VocabEntry[] = [
  {
    id: 'v-oesterreich',
    german: 'Österreich',
    display: 'Österreich',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'Austria', bg: 'Австрия' },
    pronunciation: { en: 'OES-ter-rykh', bg: 'ЬОС-те-райх' },
    example: {
      de: 'Anna kommt aus Österreich.',
      gloss: { en: 'Anna comes from Austria.', bg: 'Ана е от Австрия.' },
    },
    tags: ['country'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
  },
  {
    id: 'v-die-schweiz',
    german: 'Schweiz',
    display: 'die Schweiz',
    article: 'die',
    gender: 'f',
    wordType: 'noun',
    translation: { en: 'Switzerland', bg: 'Швейцария' },
    pronunciation: { en: 'shvyts', bg: 'швайц' },
    example: {
      de: 'Ich komme aus der Schweiz.',
      gloss: { en: 'I come from Switzerland.', bg: 'Аз съм от Швейцария.' },
    },
    tags: ['country'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L1,
    difficulty: 4,
    notes: {
      en: 'One of the few countries that keeps its article, and it changes after "aus": aus der Schweiz.',
      bg: 'Една от малкото държави, които запазват члена си, и той се мени след „aus“: aus der Schweiz.',
    },
  },
  {
    id: 'v-die-tuerkei',
    german: 'Türkei',
    display: 'die Türkei',
    article: 'die',
    gender: 'f',
    wordType: 'noun',
    translation: { en: 'Turkey', bg: 'Турция' },
    pronunciation: { en: 'tuer-KY', bg: 'тюр-КАЙ' },
    example: {
      de: 'Er kommt aus der Türkei.',
      gloss: { en: 'He comes from Turkey.', bg: 'Той е от Турция.' },
    },
    tags: ['country'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L1,
    difficulty: 4,
  },
  {
    id: 'v-england',
    german: 'England',
    display: 'England',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'England', bg: 'Англия' },
    pronunciation: { en: 'ENG-lahnt', bg: 'ЕНГ-ланд' },
    example: {
      de: 'Sie wohnt in England.',
      gloss: { en: 'She lives in England.', bg: 'Тя живее в Англия.' },
    },
    tags: ['country'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-deutsch',
    german: 'Deutsch',
    display: 'Deutsch',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'German (the language)', bg: 'немски (езикът)' },
    pronunciation: { en: 'doytch', bg: 'дойч' },
    example: {
      de: 'Ich lerne Deutsch.',
      gloss: { en: 'I am learning German.', bg: 'Уча немски.' },
    },
    tags: ['language'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
    notes: {
      en: 'Languages are nouns in German, so they take a capital letter: Deutsch, Englisch, Bulgarisch.',
      bg: 'Езиците в немския са съществителни, затова се пишат с главна буква: Deutsch, Englisch, Bulgarisch — за разлика от българското „немски“.',
    },
  },
  {
    id: 'v-bulgarisch',
    german: 'Bulgarisch',
    display: 'Bulgarisch',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'Bulgarian (the language)', bg: 'български (езикът)' },
    pronunciation: { en: 'bool-GAH-rish', bg: 'бул-ГА-риш' },
    example: {
      de: 'Ich spreche Bulgarisch und Deutsch.',
      gloss: { en: 'I speak Bulgarian and German.', bg: 'Говоря български и немски.' },
    },
    tags: ['language'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
  },
  {
    id: 'v-englisch',
    german: 'Englisch',
    display: 'Englisch',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'English (the language)', bg: 'английски (езикът)' },
    pronunciation: { en: 'ENG-lish', bg: 'ЕНГ-лиш' },
    example: {
      de: 'Sprechen Sie Englisch?',
      gloss: { en: 'Do you speak English?', bg: 'Говорите ли английски?' },
    },
    tags: ['language'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-sprechen',
    german: 'sprechen',
    display: 'sprechen',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'gesprochen' },
    translation: { en: 'to speak', bg: 'говоря' },
    pronunciation: { en: 'SHPRE-khen', bg: 'ШПРЕ-хен' },
    example: {
      de: 'Ich spreche ein wenig Deutsch.',
      gloss: { en: 'I speak a little German.', bg: 'Говоря малко немски.' },
    },
    tags: ['language', 'verb', 'irregular'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      en: 'Irregular in the du and er forms: du sprichst, er spricht — the e becomes i.',
      bg: 'Неправилен при du и er: du sprichst, er spricht — e-то става i.',
    },
  },
  {
    id: 'v-lernen',
    german: 'lernen',
    display: 'lernen',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'gelernt' },
    translation: { en: 'to learn', bg: 'уча' },
    pronunciation: { en: 'LER-nen', bg: 'ЛЕР-нен' },
    example: {
      de: 'Wir lernen Deutsch.',
      gloss: { en: 'We are learning German.', bg: 'Учим немски.' },
    },
    tags: ['language', 'verb'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-welche-sprachen-sprichst-du',
    german: 'Welche Sprachen sprichst du?',
    display: 'Welche Sprachen sprichst du?',
    wordType: 'phrase',
    translation: { en: 'Which languages do you speak?', bg: 'Какви езици говориш?' },
    pronunciation: { en: 'VEL-khe SHPRAH-khen SHPRIKHST doo', bg: 'ВЕЛ-хе ШПРА-хен ШПРИХСТ ду' },
    example: {
      de: 'Welche Sprachen sprichst du? — Bulgarisch und Deutsch.',
      gloss: {
        en: 'Which languages do you speak? — Bulgarian and German.',
        bg: 'Какви езици говориш? — Български и немски.',
      },
    },
    tags: ['language', 'question'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L1,
    difficulty: 4,
  },
];

const NATIONALITIES: VocabEntry[] = [
  {
    id: 'v-der-deutsche',
    german: 'Deutscher',
    display: 'der Deutsche',
    article: 'der',
    gender: 'm',
    plural: 'die Deutschen',
    wordType: 'noun',
    translation: { en: 'the German (man)', bg: 'германецът' },
    pronunciation: { en: 'DOY-cher', bg: 'ДОЙ-чер' },
    example: {
      de: 'Er ist Deutscher.',
      gloss: { en: 'He is German.', bg: 'Той е германец.' },
    },
    tags: ['nationality'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    related: ['v-die-deutsche'],
    notes: {
      en: 'Said without an article: "Er ist Deutscher", not "Er ist ein Deutscher" (though that also exists).',
      bg: 'Казва се без член: „Er ist Deutscher“ — точно както българското „Той е германец“.',
    },
  },
  {
    id: 'v-die-deutsche',
    german: 'Deutsche',
    display: 'die Deutsche',
    article: 'die',
    gender: 'f',
    plural: 'die Deutschen',
    wordType: 'noun',
    translation: { en: 'the German (woman)', bg: 'германката' },
    pronunciation: { en: 'DOY-che', bg: 'ДОЙ-че' },
    example: {
      de: 'Sie ist Deutsche.',
      gloss: { en: 'She is German.', bg: 'Тя е германка.' },
    },
    tags: ['nationality'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    related: ['v-der-deutsche'],
  },
  {
    id: 'v-der-bulgare',
    german: 'Bulgare',
    display: 'der Bulgare',
    article: 'der',
    gender: 'm',
    plural: 'die Bulgaren',
    wordType: 'noun',
    translation: { en: 'the Bulgarian (man)', bg: 'българинът' },
    pronunciation: { en: 'bool-GAH-re', bg: 'бул-ГА-ре' },
    example: {
      de: 'Ich bin Bulgare.',
      gloss: { en: 'I am Bulgarian.', bg: 'Аз съм българин.' },
    },
    tags: ['nationality'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-die-bulgarin'],
  },
  {
    id: 'v-die-bulgarin',
    german: 'Bulgarin',
    display: 'die Bulgarin',
    article: 'die',
    gender: 'f',
    plural: 'die Bulgarinnen',
    wordType: 'noun',
    translation: { en: 'the Bulgarian (woman)', bg: 'българката' },
    pronunciation: { en: 'bool-GAH-rin', bg: 'бул-ГА-рин' },
    example: {
      de: 'Ich bin Bulgarin.',
      gloss: { en: 'I am Bulgarian.', bg: 'Аз съм българка.' },
    },
    tags: ['nationality'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-der-bulgare'],
    notes: {
      en: 'The -in ending marks the feminine form. It is not optional: a woman says "Ich bin Bulgarin".',
      bg: 'Окончанието -in маркира женската форма, точно както българското -ка. Не е по избор: жена казва „Ich bin Bulgarin“.',
    },
  },
];

const OCCUPATIONS: VocabEntry[] = [
  {
    id: 'v-der-beruf',
    german: 'Beruf',
    display: 'der Beruf',
    article: 'der',
    gender: 'm',
    plural: 'die Berufe',
    wordType: 'noun',
    translation: { en: 'the profession, the job', bg: 'професията' },
    pronunciation: { en: 'be-ROOF', bg: 'бе-РУФ' },
    example: {
      de: 'Was sind Sie von Beruf?',
      gloss: { en: 'What do you do for a living?', bg: 'Какъв сте по професия?' },
    },
    tags: ['work'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    collocations: [
      { de: 'von Beruf', gloss: { en: 'by profession', bg: 'по професия' } },
      { de: 'Was machst du beruflich?', gloss: { en: 'What do you do for work?', bg: 'С какво се занимаваш?' } },
    ],
    notes: {
      bg: 'Родът не съвпада: der Beruf е от мъжки род, а българското „професия“ е от женски род.',
    },
  },
  {
    id: 'v-der-lehrer',
    german: 'Lehrer',
    display: 'der Lehrer',
    article: 'der',
    gender: 'm',
    plural: 'die Lehrer',
    wordType: 'noun',
    translation: { en: 'the teacher (man)', bg: 'учителят' },
    pronunciation: { en: 'LAY-rer', bg: 'ЛЕ-рер' },
    example: {
      de: 'Ich bin Lehrer.',
      gloss: { en: 'I am a teacher.', bg: 'Аз съм учител.' },
    },
    tags: ['work', 'occupation'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-die-lehrerin'],
    notes: {
      en: 'A bare profession takes no article: "Ich bin Lehrer", not "Ich bin ein Lehrer".',
      bg: 'Професия сама по себе си е без член: „Ich bin Lehrer“, а не „Ich bin ein Lehrer“ — също като българското „Аз съм учител“.',
    },
  },
  {
    id: 'v-die-lehrerin',
    german: 'Lehrerin',
    display: 'die Lehrerin',
    article: 'die',
    gender: 'f',
    plural: 'die Lehrerinnen',
    wordType: 'noun',
    translation: { en: 'the teacher (woman)', bg: 'учителката' },
    pronunciation: { en: 'LAY-re-rin', bg: 'ЛЕ-ре-рин' },
    example: {
      de: 'Meine Mutter ist Lehrerin.',
      gloss: { en: 'My mother is a teacher.', bg: 'Майка ми е учителка.' },
    },
    tags: ['work', 'occupation'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-der-lehrer'],
  },
  {
    id: 'v-der-arzt',
    german: 'Arzt',
    display: 'der Arzt',
    article: 'der',
    gender: 'm',
    plural: 'die Ärzte',
    wordType: 'noun',
    translation: { en: 'the doctor (man)', bg: 'лекарят' },
    pronunciation: { en: 'ahrtst', bg: 'арцт' },
    example: {
      de: 'Mein Vater ist Arzt.',
      gloss: { en: 'My father is a doctor.', bg: 'Баща ми е лекар.' },
    },
    tags: ['work', 'occupation'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    related: ['v-die-aerztin'],
    notes: {
      en: 'The plural takes an umlaut: der Arzt → die Ärzte.',
      bg: 'Множественото число взима умлаут: der Arzt → die Ärzte.',
    },
  },
  {
    id: 'v-die-aerztin',
    german: 'Ärztin',
    display: 'die Ärztin',
    article: 'die',
    gender: 'f',
    plural: 'die Ärztinnen',
    wordType: 'noun',
    translation: { en: 'the doctor (woman)', bg: 'лекарката' },
    pronunciation: { en: 'AIRTS-tin', bg: 'ЕРЦ-тин' },
    example: {
      de: 'Sie ist Ärztin.',
      gloss: { en: 'She is a doctor.', bg: 'Тя е лекарка.' },
    },
    tags: ['work', 'occupation'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    related: ['v-der-arzt'],
  },
  {
    id: 'v-der-student',
    german: 'Student',
    display: 'der Student',
    article: 'der',
    gender: 'm',
    plural: 'die Studenten',
    wordType: 'noun',
    translation: { en: 'the student (at university, man)', bg: 'студентът' },
    pronunciation: { en: 'shtoo-DENT', bg: 'щу-ДЕНТ' },
    example: {
      de: 'Ich bin Student.',
      gloss: { en: 'I am a student.', bg: 'Аз съм студент.' },
    },
    tags: ['work', 'occupation'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'Only for university. A school pupil is "der Schüler".',
      bg: 'Само за университет. Ученик в училище е „der Schüler“.',
    },
  },
  {
    id: 'v-der-ingenieur',
    german: 'Ingenieur',
    display: 'der Ingenieur',
    article: 'der',
    gender: 'm',
    plural: 'die Ingenieure',
    wordType: 'noun',
    translation: { en: 'the engineer', bg: 'инженерът' },
    pronunciation: { en: 'in-zhe-NYOER', bg: 'ин-же-НЬОР' },
    example: {
      de: 'Er ist Ingenieur.',
      gloss: { en: 'He is an engineer.', bg: 'Той е инженер.' },
    },
    tags: ['work', 'occupation'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    notes: {
      en: 'A French loanword, so it keeps a French sound: in-zhe-NYOER.',
      bg: 'Заемка от френски, затова запазва френското звучене: ин-же-НЬОР.',
    },
  },
  {
    id: 'v-die-verkaeuferin',
    german: 'Verkäuferin',
    display: 'die Verkäuferin',
    article: 'die',
    gender: 'f',
    plural: 'die Verkäuferinnen',
    wordType: 'noun',
    translation: { en: 'the shop assistant (woman)', bg: 'продавачката' },
    pronunciation: { en: 'fer-KOY-fe-rin', bg: 'фер-КОЙ-фе-рин' },
    example: {
      de: 'Sie ist Verkäuferin.',
      gloss: { en: 'She is a shop assistant.', bg: 'Тя е продавачка.' },
    },
    tags: ['work', 'occupation'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
  },
  {
    id: 'v-was-machst-du-beruflich',
    german: 'Was machst du beruflich?',
    display: 'Was machst du beruflich?',
    wordType: 'phrase',
    translation: { en: 'What do you do for work?', bg: 'С какво се занимаваш?' },
    pronunciation: { en: 'vas MAKHST doo be-ROOF-likh', bg: 'вас МАХСТ ду бе-РУФ-лих' },
    example: {
      de: 'Was machst du beruflich? — Ich bin Ingenieur.',
      gloss: {
        en: 'What do you do for work? — I am an engineer.',
        bg: 'С какво се занимаваш? — Аз съм инженер.',
      },
    },
    tags: ['work', 'question'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    collocations: [
      { de: 'Was sind Sie von Beruf?', gloss: { en: 'What is your profession? (formal)', bg: 'Какъв сте по професия? (учтиво)' } },
    ],
  },
  {
    id: 'v-arbeiten',
    german: 'arbeiten',
    display: 'arbeiten',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'gearbeitet' },
    translation: { en: 'to work', bg: 'работя' },
    pronunciation: { en: 'AR-by-ten', bg: 'АР-бай-тен' },
    example: {
      de: 'Ich arbeite in Hamburg.',
      gloss: { en: 'I work in Hamburg.', bg: 'Работя в Хамбург.' },
    },
    tags: ['work', 'verb'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'The stem ends in -t, so an extra e appears: du arbeitest, er arbeitet.',
      bg: 'Основата завършва на -t, затова се появява допълнително e: du arbeitest, er arbeitet.',
    },
  },
];

const FAMILY: VocabEntry[] = [
  {
    id: 'v-die-familie',
    german: 'Familie',
    display: 'die Familie',
    article: 'die',
    gender: 'f',
    plural: 'die Familien',
    wordType: 'noun',
    translation: { en: 'the family', bg: 'семейството' },
    pronunciation: { en: 'fa-MEE-lee-e', bg: 'фа-МИ-ли-е' },
    example: {
      de: 'Meine Familie wohnt in Sofia.',
      gloss: { en: 'My family lives in Sofia.', bg: 'Семейството ми живее в София.' },
    },
    tags: ['family'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    notes: {
      bg: 'Родът не съвпада: die Familie е от женски род, а българското „семейство“ е от среден род.',
    },
  },
  {
    id: 'v-die-mutter',
    german: 'Mutter',
    display: 'die Mutter',
    article: 'die',
    gender: 'f',
    plural: 'die Mütter',
    wordType: 'noun',
    translation: { en: 'the mother', bg: 'майката' },
    pronunciation: { en: 'MOO-ter', bg: 'МУ-тер' },
    example: {
      de: 'Meine Mutter ist Lehrerin.',
      gloss: { en: 'My mother is a teacher.', bg: 'Майка ми е учителка.' },
    },
    tags: ['family'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L3,
    difficulty: 1,
    notes: {
      en: 'The plural only changes the vowel: die Mutter → die Mütter.',
      bg: 'Множественото число мени само гласната: die Mutter → die Mütter.',
    },
  },
  {
    id: 'v-der-vater',
    german: 'Vater',
    display: 'der Vater',
    article: 'der',
    gender: 'm',
    plural: 'die Väter',
    wordType: 'noun',
    translation: { en: 'the father', bg: 'бащата' },
    pronunciation: { en: 'FAH-ter', bg: 'ФА-тер' },
    example: {
      de: 'Mein Vater arbeitet in Berlin.',
      gloss: { en: 'My father works in Berlin.', bg: 'Баща ми работи в Берлин.' },
    },
    tags: ['family'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L3,
    difficulty: 1,
    notes: {
      en: 'Starts with an f sound, not a v: FAH-ter.',
      bg: 'Започва с „ф“, не с „в“: ФА-тер.',
    },
  },
  {
    id: 'v-die-eltern',
    german: 'Eltern',
    display: 'die Eltern',
    article: 'die',
    gender: 'f',
    plural: 'die Eltern',
    wordType: 'noun',
    translation: { en: 'the parents', bg: 'родителите' },
    pronunciation: { en: 'EL-tern', bg: 'ЕЛ-терн' },
    example: {
      de: 'Meine Eltern wohnen in Bulgarien.',
      gloss: { en: 'My parents live in Bulgaria.', bg: 'Родителите ми живеят в България.' },
    },
    tags: ['family'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
    notes: {
      en: 'Plural only — there is no singular "Elter". It always takes a plural verb: meine Eltern wohnen.',
      bg: 'Само в множествено число — няма „Elter“ в единствено. Винаги взима глагол в множествено: meine Eltern wohnen.',
    },
  },
  {
    id: 'v-der-bruder',
    german: 'Bruder',
    display: 'der Bruder',
    article: 'der',
    gender: 'm',
    plural: 'die Brüder',
    wordType: 'noun',
    translation: { en: 'the brother', bg: 'братът' },
    pronunciation: { en: 'BROO-der', bg: 'БРУ-дер' },
    example: {
      de: 'Ich habe einen Bruder.',
      gloss: { en: 'I have a brother.', bg: 'Имам един брат.' },
    },
    tags: ['family'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    notes: {
      en: 'The umlaut in the plural changes the meaning, so it matters: der Bruder is one, die Brüder is several.',
      bg: 'Умлаутът в множественото число променя значението, затова е важен: der Bruder е един, die Brüder са няколко.',
    },
  },
  {
    id: 'v-die-schwester',
    german: 'Schwester',
    display: 'die Schwester',
    article: 'die',
    gender: 'f',
    plural: 'die Schwestern',
    wordType: 'noun',
    translation: { en: 'the sister', bg: 'сестрата' },
    pronunciation: { en: 'SHVES-ter', bg: 'ШВЕС-тер' },
    example: {
      de: 'Ich habe eine Schwester.',
      gloss: { en: 'I have a sister.', bg: 'Имам една сестра.' },
    },
    tags: ['family'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-haben',
    german: 'haben',
    display: 'haben',
    wordType: 'verb',
    perfect: { auxiliary: 'haben', participle: 'gehabt' },
    translation: { en: 'to have', bg: 'имам' },
    pronunciation: { en: 'HAH-ben', bg: 'ХА-бен' },
    example: {
      de: 'Ich habe zwei Kinder.',
      gloss: { en: 'I have two children.', bg: 'Имам две деца.' },
    },
    tags: ['family', 'verb', 'irregular'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    notes: {
      en: 'Slightly irregular: du hast and er hat drop the b.',
      bg: 'Леко неправилен: du hast и er hat изпускат b-то.',
    },
  },
  {
    id: 'v-hast-du-geschwister',
    german: 'Hast du Geschwister?',
    display: 'Hast du Geschwister?',
    wordType: 'phrase',
    translation: { en: 'Do you have brothers or sisters?', bg: 'Имаш ли братя и сестри?' },
    pronunciation: { en: 'hast doo ge-SHVIS-ter', bg: 'хаст ду ге-ШВИС-тер' },
    example: {
      de: 'Hast du Geschwister? — Ja, einen Bruder.',
      gloss: {
        en: 'Do you have brothers or sisters? — Yes, one brother.',
        bg: 'Имаш ли братя и сестри? — Да, един брат.',
      },
    },
    tags: ['family', 'question'],
    level: 'pre-a1',
    unitId: U,
    lessonId: L3,
    difficulty: 4,
    notes: {
      en: '"Geschwister" is one word for brothers and sisters together, and it is always plural.',
      bg: '„Geschwister“ е една дума за братя и сестри заедно — нещо, което българският не има — и е винаги в множествено число.',
    },
  },
];

export const PERSONAL_VOCAB: VocabEntry[] = [
  ...COUNTRIES_AND_LANGUAGES,
  ...NATIONALITIES,
  ...OCCUPATIONS,
  ...FAMILY,
];
