import type { VocabEntry } from '../types.ts';

/**
 * Places, transport and directions (A1 Unit 5).
 *
 * This unit carries the dative, which is the hardest step in A1, so the
 * vocabulary is chosen to make that step survivable. Almost every noun here is
 * a place you go *to* or travel *by*, which means every single word is another
 * repetition of `zum`, `zur` or `mit dem` — the three forms that actually
 * matter at this level.
 *
 * The genders are not evenly spread and that is deliberate: masculine and
 * neuter both become `dem`, so a unit heavy in `der Bahnhof` and `das Kino`
 * teaches one form twice before the feminine `der` arrives to complicate it.
 */

const U = 'a1-u5';
const L1 = 'a1-u5-l1';
const L2 = 'a1-u5-l2';
const L3 = 'a1-u5-l3';

/* ------------------------------------------------------------------ *
 * Lesson 1 — places in town
 * ------------------------------------------------------------------ */

const PLACES: VocabEntry[] = [
  {
    id: 'v-bahnhof',
    german: 'Bahnhof',
    display: 'der Bahnhof',
    article: 'der',
    gender: 'm',
    plural: 'die Bahnhöfe',
    wordType: 'noun',
    translation: { en: 'railway station', bg: 'гара' },
    pronunciation: { en: 'BAHN-hohf', bg: 'БАН-хоф' },
    example: {
      de: 'Der Bahnhof ist sehr groß.',
      gloss: { en: 'The station is very big.', bg: 'Гарата е много голяма.' },
    },
    tags: ['place', 'transport'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Родовете се разминават: „гара“ е женски род, а der Bahnhof е мъжки. Това ще има значение веднага — „до гарата“ е zum Bahnhof, не zur.',
      en: 'Bahn (railway) plus Hof (yard). Masculine, which decides whether you say zum or zur.',
    },
  },
  {
    id: 'v-haltestelle',
    german: 'Haltestelle',
    display: 'die Haltestelle',
    article: 'die',
    gender: 'f',
    plural: 'die Haltestellen',
    wordType: 'noun',
    translation: { en: 'stop (bus, tram)', bg: 'спирка' },
    pronunciation: { en: 'HAL-te-shte-le', bg: 'ХАЛ-те-ще-ле' },
    example: {
      de: 'Die Haltestelle ist hier rechts.',
      gloss: { en: 'The stop is here on the right.', bg: 'Спирката е тук вдясно.' },
    },
    tags: ['place', 'transport'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      en: 'halten (to stop) plus Stelle (place). Feminine, so it takes zur.',
      bg: 'halten (спирам) плюс Stelle (място). Женски род, значи взима zur.',
    },
  },
  {
    id: 'v-strasse',
    german: 'Straße',
    display: 'die Straße',
    article: 'die',
    gender: 'f',
    plural: 'die Straßen',
    wordType: 'noun',
    translation: { en: 'street', bg: 'улица' },
    pronunciation: { en: 'SHTRAH-se', bg: 'ЩРА-се' },
    example: {
      de: 'Die erste Straße links.',
      gloss: { en: 'The first street on the left.', bg: 'Първата улица вляво.' },
    },
    tags: ['place'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'Written with ß. You will see it abbreviated to Str. on every address in Germany.',
      bg: 'Пише се с ß. Ще го видиш съкратено като Str. на всеки немски адрес.',
    },
  },
  {
    id: 'v-apotheke',
    german: 'Apotheke',
    display: 'die Apotheke',
    article: 'die',
    gender: 'f',
    plural: 'die Apotheken',
    wordType: 'noun',
    translation: { en: 'pharmacy', bg: 'аптека' },
    pronunciation: { en: 'a-po-TAY-ke', bg: 'а-по-ТЕ-ке' },
    example: {
      de: 'Wo ist die Apotheke?',
      gloss: { en: 'Where is the pharmacy?', bg: 'Къде е аптеката?' },
    },
    tags: ['place'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Тук двата езика съвпадат по звучене и по род — „аптека“ и die Apotheke са и двете женски. Рядко удоволствие.',
    },
  },
  {
    id: 'v-post',
    german: 'Post',
    display: 'die Post',
    article: 'die',
    gender: 'f',
    wordType: 'noun',
    translation: { en: 'post office, post', bg: 'поща' },
    pronunciation: { en: 'post', bg: 'пост' },
    example: {
      de: 'Ich gehe zur Post.',
      gloss: { en: 'I am going to the post office.', bg: 'Отивам до пощата.' },
    },
    tags: ['place'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
  },
  {
    id: 'v-bank',
    german: 'Bank',
    display: 'die Bank',
    article: 'die',
    gender: 'f',
    plural: 'die Banken',
    wordType: 'noun',
    translation: { en: 'bank', bg: 'банка' },
    pronunciation: { en: 'bank', bg: 'банк' },
    example: {
      de: 'Die Bank ist neben der Post.',
      gloss: { en: 'The bank is next to the post office.', bg: 'Банката е до пощата.' },
    },
    tags: ['place'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      en: 'Two plurals, two meanings: die Banken are banks, die Bänke are benches. Same word, and the plural is the only thing that separates them.',
      bg: 'Две множествени числа, две значения: die Banken са банки, die Bänke са пейки. Една и съща дума, а множественото ги разделя.',
    },
  },
  {
    id: 'v-kino',
    german: 'Kino',
    display: 'das Kino',
    article: 'das',
    gender: 'n',
    plural: 'die Kinos',
    wordType: 'noun',
    translation: { en: 'cinema', bg: 'кино' },
    pronunciation: { en: 'KEE-no', bg: 'КИ-но' },
    example: {
      de: 'Wir gehen ins Kino.',
      gloss: { en: 'We are going to the cinema.', bg: 'Отиваме на кино.' },
    },
    tags: ['place', 'free-time'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-restaurant',
    german: 'Restaurant',
    display: 'das Restaurant',
    article: 'das',
    gender: 'n',
    plural: 'die Restaurants',
    wordType: 'noun',
    translation: { en: 'restaurant', bg: 'ресторант' },
    pronunciation: { en: 'res-to-RAHNG', bg: 'рес-то-РАН' },
    example: {
      de: 'Das Restaurant ist sehr gut.',
      gloss: { en: 'The restaurant is very good.', bg: 'Ресторантът е много добър.' },
    },
    tags: ['place'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'Borrowed from French and still pronounced that way: the final t is silent.',
      bg: 'Заета от френски и още се произнася така: крайното t не се чете.',
    },
  },
  {
    id: 'v-park',
    german: 'Park',
    display: 'der Park',
    article: 'der',
    gender: 'm',
    plural: 'die Parks',
    wordType: 'noun',
    translation: { en: 'park', bg: 'парк' },
    pronunciation: { en: 'park', bg: 'парк' },
    example: {
      de: 'Der Park ist neben dem Museum.',
      gloss: { en: 'The park is next to the museum.', bg: 'Паркът е до музея.' },
    },
    tags: ['place'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-museum',
    german: 'Museum',
    display: 'das Museum',
    article: 'das',
    gender: 'n',
    plural: 'die Museen',
    wordType: 'noun',
    translation: { en: 'museum', bg: 'музей' },
    pronunciation: { en: 'moo-ZAY-oom', bg: 'му-ЗЕ-ум' },
    example: {
      de: 'Das Museum ist heute zu.',
      gloss: { en: 'The museum is closed today.', bg: 'Музеят е затворен днес.' },
    },
    tags: ['place'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      bg: 'Родовете се разминават: „музей“ е мъжки, das Museum е среден. Множественото е неочаквано: die Museen.',
      en: 'An unusual plural: die Museen.',
    },
  },
  {
    id: 'v-hier',
    german: 'hier',
    display: 'hier',
    wordType: 'adverb',
    translation: { en: 'here', bg: 'тук' },
    pronunciation: { en: 'heer', bg: 'хир' },
    example: {
      de: 'Die Haltestelle ist hier.',
      gloss: { en: 'The stop is here.', bg: 'Спирката е тук.' },
    },
    tags: ['adverb', 'place'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
  {
    id: 'v-dort',
    german: 'dort',
    display: 'dort',
    wordType: 'adverb',
    translation: { en: 'there', bg: 'там' },
    pronunciation: { en: 'dort', bg: 'дорт' },
    example: {
      de: 'Das Kino ist dort.',
      gloss: { en: 'The cinema is there.', bg: 'Киното е там.' },
    },
    tags: ['adverb', 'place'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 1,
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 2 — getting there
 * ------------------------------------------------------------------ */

const TRANSPORT: VocabEntry[] = [
  {
    id: 'v-bus',
    german: 'Bus',
    display: 'der Bus',
    article: 'der',
    gender: 'm',
    plural: 'die Busse',
    wordType: 'noun',
    translation: { en: 'bus', bg: 'автобус' },
    pronunciation: { en: 'boos', bg: 'бус' },
    example: {
      de: 'Ich fahre mit dem Bus.',
      gloss: { en: 'I go by bus.', bg: 'Пътувам с автобуса.' },
    },
    tags: ['transport'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
  },
  {
    id: 'v-zug',
    german: 'Zug',
    display: 'der Zug',
    article: 'der',
    gender: 'm',
    plural: 'die Züge',
    wordType: 'noun',
    translation: { en: 'train', bg: 'влак' },
    pronunciation: { en: 'tsook', bg: 'цук' },
    example: {
      de: 'Der Zug fährt um acht Uhr.',
      gloss: { en: 'The train leaves at eight o’clock.', bg: 'Влакът тръгва в осем часа.' },
    },
    tags: ['transport'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
  },
  {
    id: 'v-auto',
    german: 'Auto',
    display: 'das Auto',
    article: 'das',
    gender: 'n',
    plural: 'die Autos',
    wordType: 'noun',
    translation: { en: 'car', bg: 'кола, автомобил' },
    pronunciation: { en: 'OW-to', bg: 'АУ-то' },
    example: {
      de: 'Wir fahren mit dem Auto.',
      gloss: { en: 'We are going by car.', bg: 'Пътуваме с колата.' },
    },
    tags: ['transport'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 1,
    notes: {
      bg: 'Родовете се разминават: „кола“ е женски, das Auto е среден. За щастие средният и мъжкият дават една и съща дателна форма — dem.',
    },
  },
  {
    id: 'v-zu-fuss',
    german: 'zu Fuß',
    display: 'zu Fuß',
    wordType: 'phrase',
    translation: { en: 'on foot', bg: 'пеша' },
    pronunciation: { en: 'tsoo FOOS', bg: 'цу ФУС' },
    example: {
      de: 'Ich gehe zu Fuß.',
      gloss: { en: 'I go on foot.', bg: 'Отивам пеша.' },
    },
    tags: ['transport', 'phrase'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'The one way of travelling that does not take mit: zu Fuß, and the verb is gehen rather than fahren.',
      bg: 'Единственият начин на придвижване, който не взима mit: zu Fuß, а глаголът е gehen, не fahren.',
    },
  },
  {
    id: 'v-gehen',
    german: 'gehen',
    display: 'gehen',
    wordType: 'verb',
    translation: { en: 'to go (on foot)', bg: 'отивам, ходя (пеша)' },
    pronunciation: { en: 'GAY-en', bg: 'ГЕ-ен' },
    example: {
      de: 'Ich gehe zur Post.',
      gloss: { en: 'I am going to the post office.', bg: 'Отивам до пощата.' },
    },
    tags: ['verb', 'transport'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    related: ['v-fahren'],
    notes: {
      bg: 'Българското „отивам“ се разделя на две на немски: gehen пеша, fahren с превозно средство. Ако кажеш „Ich gehe nach Berlin“, значи буквално тръгваш пеша.',
      en: 'gehen is on foot only. "Ich gehe nach Berlin" means you are walking there.',
    },
  },
  {
    id: 'v-mit',
    german: 'mit',
    display: 'mit',
    wordType: 'preposition',
    translation: { en: 'with, by (transport)', bg: 'с' },
    pronunciation: { en: 'mit', bg: 'мит' },
    example: {
      de: 'Ich fahre mit dem Zug.',
      gloss: { en: 'I go by train.', bg: 'Пътувам с влака.' },
    },
    tags: ['preposition', 'dative'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    notes: {
      en: 'Always takes the dative, with no exceptions. That makes it the easiest preposition to practise the dative with.',
      bg: 'Винаги взима дателен падеж, без изключения. Точно затова е най-удобният предлог за упражняване на дателния.',
    },
  },
  {
    id: 'v-zu-prep',
    german: 'zu',
    display: 'zu',
    wordType: 'preposition',
    translation: { en: 'to (a place)', bg: 'до, към' },
    pronunciation: { en: 'tsoo', bg: 'цу' },
    example: {
      de: 'Ich gehe zum Bahnhof.',
      gloss: { en: 'I am going to the station.', bg: 'Отивам до гарата.' },
    },
    tags: ['preposition', 'dative'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    notes: {
      en: 'Also always dative, and it contracts: zu dem becomes zum, zu der becomes zur. Nobody says the long forms.',
      bg: 'Също винаги дателен и се слива: zu dem става zum, zu der става zur. Дългите форми никой не ги казва.',
    },
  },
  {
    id: 'v-wie-lange',
    german: 'Wie lange',
    display: 'Wie lange?',
    wordType: 'phrase',
    translation: { en: 'How long?', bg: 'Колко време?' },
    pronunciation: { en: 'vee LANG-e', bg: 'ви ЛАН-ге' },
    example: {
      de: 'Wie lange fährt der Bus?',
      gloss: { en: 'How long does the bus take?', bg: 'Колко време пътува автобусът?' },
    },
    tags: ['question', 'phrase'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 3 — directions
 * ------------------------------------------------------------------ */

const DIRECTIONS: VocabEntry[] = [
  {
    id: 'v-links',
    german: 'links',
    display: 'links',
    wordType: 'adverb',
    translation: { en: 'left, on the left', bg: 'вляво' },
    pronunciation: { en: 'links', bg: 'линкс' },
    example: {
      de: 'Die Apotheke ist links.',
      gloss: { en: 'The pharmacy is on the left.', bg: 'Аптеката е вляво.' },
    },
    tags: ['directions'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    related: ['v-rechts'],
  },
  {
    id: 'v-rechts',
    german: 'rechts',
    display: 'rechts',
    wordType: 'adverb',
    translation: { en: 'right, on the right', bg: 'вдясно' },
    pronunciation: { en: 'rekhts', bg: 'рехтс' },
    example: {
      de: 'Die Bank ist rechts.',
      gloss: { en: 'The bank is on the right.', bg: 'Банката е вдясно.' },
    },
    tags: ['directions'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    related: ['v-links'],
    notes: {
      en: 'Also means "correct" in other contexts, but for directions it is simply right.',
      bg: 'В други контексти значи и „правилно“, но при посоки е просто „вдясно“.',
    },
  },
  {
    id: 'v-geradeaus',
    german: 'geradeaus',
    display: 'geradeaus',
    wordType: 'adverb',
    translation: { en: 'straight on', bg: 'направо' },
    pronunciation: { en: 'ge-RAH-de-ows', bg: 'ге-РА-де-аус' },
    example: {
      de: 'Gehen Sie geradeaus.',
      gloss: { en: 'Go straight on.', bg: 'Вървете направо.' },
    },
    tags: ['directions'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
  },
  {
    id: 'v-neben',
    german: 'neben',
    display: 'neben',
    wordType: 'preposition',
    translation: { en: 'next to', bg: 'до, до страната на' },
    pronunciation: { en: 'NAY-ben', bg: 'НЕ-бен' },
    example: {
      de: 'Die Bank ist neben der Post.',
      gloss: { en: 'The bank is next to the post office.', bg: 'Банката е до пощата.' },
    },
    tags: ['preposition', 'directions', 'dative'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 4,
    notes: {
      en: 'When it answers "where is it", neben takes the dative: neben dem Kino, neben der Post.',
      bg: 'Когато отговаря на „къде е“, neben взима дателен падеж: neben dem Kino, neben der Post.',
    },
  },
  {
    id: 'v-erste',
    german: 'erste',
    display: 'die erste',
    wordType: 'numeral',
    translation: { en: 'the first', bg: 'първата' },
    pronunciation: { en: 'AIRS-te', bg: 'ЕРС-те' },
    example: {
      de: 'Nehmen Sie die erste Straße links.',
      gloss: { en: 'Take the first street on the left.', bg: 'Вземете първата улица вляво.' },
    },
    tags: ['directions', 'numeral'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
    notes: {
      en: 'Ordinal numbers get an ending. You only need the first two here: die erste, die zweite.',
      bg: 'Редните числителни взимат окончание. Тук ти трябват само първите две: die erste, die zweite.',
    },
  },
  {
    id: 'v-zweite',
    german: 'zweite',
    display: 'die zweite',
    wordType: 'numeral',
    translation: { en: 'the second', bg: 'втората' },
    pronunciation: { en: 'TSVY-te', bg: 'ЦВАЙ-те' },
    example: {
      de: 'Die zweite Straße rechts.',
      gloss: { en: 'The second street on the right.', bg: 'Втората улица вдясно.' },
    },
    tags: ['directions', 'numeral'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
    related: ['v-erste'],
  },
  {
    id: 'v-weit',
    german: 'weit',
    display: 'weit',
    wordType: 'adjective',
    translation: { en: 'far', bg: 'далеч' },
    pronunciation: { en: 'vyte', bg: 'вайт' },
    example: {
      de: 'Ist es weit?',
      gloss: { en: 'Is it far?', bg: 'Далеч ли е?' },
    },
    tags: ['directions', 'adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    notes: {
      en: '"Ist es weit?" is the whole question, and worth knowing before you need it.',
      bg: '„Ist es weit?“ е целият въпрос и си струва да го знаеш, преди да ти потрябва.',
    },
  },
  {
    id: 'v-entschuldigen-sie',
    german: 'Entschuldigen Sie',
    display: 'Entschuldigen Sie',
    wordType: 'phrase',
    translation: { en: 'Excuse me', bg: 'Извинете' },
    pronunciation: { en: 'ent-SHOOL-di-gen zee', bg: 'ент-ШУЛ-ди-ген зи' },
    example: {
      de: 'Entschuldigen Sie, wo ist der Bahnhof?',
      gloss: { en: 'Excuse me, where is the station?', bg: 'Извинете, къде е гарата?' },
    },
    tags: ['phrase', 'politeness'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
    notes: {
      en: 'The polite way to open. You already know Entschuldigung, which is the noun; this is the verb form, and it keeps Sie.',
      bg: 'Учтивото начало. Вече знаеш Entschuldigung — съществителното; това е глаголната форма и тя запазва Sie.',
    },
  },
];

export const TOWN_VOCAB: VocabEntry[] = [...PLACES, ...TRANSPORT, ...DIRECTIONS];
