import type { VocabEntry } from '../types.ts';

/**
 * Work, study and free time (A1 Unit 4).
 *
 * The unit this serves ends with the four conjunctions — und, aber, oder, denn
 * — so the vocabulary is deliberately made of things a learner will want to put
 * in the same sentence: a job and an opinion about it, a hobby and a reason for
 * it. Words that cannot be joined to anything make poor material for a lesson
 * about joining.
 *
 * Verbs dominate, because free time is something you *do*. Several are
 * irregular in exactly the way German verbs are irregular at A1 (lesen → du
 * liest, fahren → du fährst), which is the last stem-change pattern the level
 * needs.
 */

const U = 'a1-u4';
const L1 = 'a1-u4-l1';
const L2 = 'a1-u4-l2';
const L3 = 'a1-u4-l3';

/* ------------------------------------------------------------------ *
 * Lesson 1 — work and study
 * ------------------------------------------------------------------ */

const WORK: VocabEntry[] = [
  {
    id: 'v-firma',
    german: 'Firma',
    display: 'die Firma',
    article: 'die',
    gender: 'f',
    plural: 'die Firmen',
    wordType: 'noun',
    translation: { en: 'company, firm', bg: 'фирма' },
    pronunciation: { en: 'FEER-mah', bg: 'ФИР-ма' },
    example: {
      de: 'Ich arbeite bei einer Firma in Berlin.',
      gloss: { en: 'I work at a company in Berlin.', bg: 'Работя във фирма в Берлин.' },
    },
    tags: ['work'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      en: 'The plural changes the ending, not just the article: die Firma, die Firmen.',
      bg: 'Множественото число сменя окончанието, не само члена: die Firma, die Firmen.',
    },
  },
  {
    id: 'v-buero',
    german: 'Büro',
    display: 'das Büro',
    article: 'das',
    gender: 'n',
    plural: 'die Büros',
    wordType: 'noun',
    translation: { en: 'office', bg: 'офис' },
    pronunciation: { en: 'bue-ROH', bg: 'бю-РО' },
    example: {
      de: 'Mein Büro ist klein.',
      gloss: { en: 'My office is small.', bg: 'Офисът ми е малък.' },
    },
    tags: ['work'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Родовете се разминават: „офис“ е мъжки род, а das Büro е среден. Ударението пада на втората сричка: бю-РО.',
    },
  },
  {
    id: 'v-chef',
    german: 'Chef',
    display: 'der Chef',
    article: 'der',
    gender: 'm',
    plural: 'die Chefs',
    wordType: 'noun',
    translation: { en: 'boss', bg: 'шеф' },
    pronunciation: { en: 'shef', bg: 'шеф' },
    example: {
      de: 'Mein Chef ist sehr nett.',
      gloss: { en: 'My boss is very nice.', bg: 'Шефът ми е много мил.' },
    },
    tags: ['work', 'people'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'Not a cook. German Chef means boss; the kitchen one is der Koch. A false friend worth catching early.',
      bg: 'Не е готвач. Немското Chef значи шеф, началник; готвачът е der Koch.',
    },
  },
  {
    id: 'v-studieren',
    german: 'studieren',
    display: 'studieren',
    wordType: 'verb',
    translation: { en: 'to study (at university)', bg: 'следвам, уча в университет' },
    pronunciation: { en: 'shtoo-DEE-ren', bg: 'щу-ДИ-рен' },
    example: {
      de: 'Ich studiere in München.',
      gloss: { en: 'I study in Munich.', bg: 'Следвам в Мюнхен.' },
    },
    tags: ['verb', 'study'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    related: ['v-lernen'],
    notes: {
      en: 'studieren is university only. For learning anything else — a language, a skill — German uses lernen.',
      bg: 'studieren е само за университет. За учене на нещо друго — език, умение — немският използва lernen. Българското „уча“ върши и двете.',
    },
  },
  {
    id: 'v-universitaet',
    german: 'Universität',
    display: 'die Universität',
    article: 'die',
    gender: 'f',
    plural: 'die Universitäten',
    wordType: 'noun',
    translation: { en: 'university', bg: 'университет' },
    pronunciation: { en: 'oo-nee-ver-zi-TAYT', bg: 'у-ни-вер-зи-ТЕТ' },
    example: {
      de: 'Die Universität ist groß.',
      gloss: { en: 'The university is big.', bg: 'Университетът е голям.' },
    },
    tags: ['study'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      en: 'Everyone says "die Uni". Use the short form and you will sound like a student rather than a form.',
      bg: 'Всички казват „die Uni“. Използвай късата форма и ще звучиш като студент, а не като формуляр.',
    },
  },
  {
    id: 'v-schule',
    german: 'Schule',
    display: 'die Schule',
    article: 'die',
    gender: 'f',
    plural: 'die Schulen',
    wordType: 'noun',
    translation: { en: 'school', bg: 'училище' },
    pronunciation: { en: 'SHOO-le', bg: 'ШУ-ле' },
    example: {
      de: 'Meine Kinder gehen in die Schule.',
      gloss: { en: 'My children go to school.', bg: 'Децата ми ходят на училище.' },
    },
    tags: ['study'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      bg: 'Родовете се разминават: „училище“ е среден род, а die Schule е женски.',
    },
  },
  {
    id: 'v-als',
    german: 'als',
    display: 'als',
    wordType: 'preposition',
    translation: { en: 'as (in a role)', bg: 'като (по професия)' },
    pronunciation: { en: 'als', bg: 'алс' },
    example: {
      de: 'Ich arbeite als Lehrerin.',
      gloss: { en: 'I work as a teacher.', bg: 'Работя като учителка.' },
    },
    tags: ['work', 'grammar'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 3,
    notes: {
      en: 'No article after it: "Ich arbeite als Lehrerin", never "als eine Lehrerin". Same rule you met with "Ich bin Lehrerin".',
      bg: 'Без член след него: „Ich arbeite als Lehrerin“, никога „als eine Lehrerin“. Същото правило като при „Ich bin Lehrerin“.',
    },
  },
  {
    id: 'v-zeit',
    german: 'Zeit',
    display: 'die Zeit',
    article: 'die',
    gender: 'f',
    plural: 'die Zeiten',
    wordType: 'noun',
    translation: { en: 'time', bg: 'време' },
    pronunciation: { en: 'tsyte', bg: 'цайт' },
    example: {
      de: 'Ich habe keine Zeit.',
      gloss: { en: 'I have no time.', bg: 'Нямам време.' },
    },
    tags: ['time'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: '"Ich habe keine Zeit" is worth learning whole — it is the most common excuse in any language.',
      bg: '„Ich habe keine Zeit“ си струва да се научи наведнъж. Внимавай обаче: немският има две думи за българското „време“ — Zeit за часовниковото, Wetter за навън.',
    },
  },
  {
    id: 'v-frei',
    german: 'frei',
    display: 'frei',
    wordType: 'adjective',
    translation: { en: 'free, not busy', bg: 'свободен' },
    pronunciation: { en: 'fry', bg: 'фрай' },
    example: {
      de: 'Am Samstag bin ich frei.',
      gloss: { en: 'On Saturday I am free.', bg: 'В събота съм свободен.' },
    },
    tags: ['adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L1,
    difficulty: 2,
    notes: {
      en: 'Free as in available, not free as in costing nothing — that is kostenlos or gratis.',
      bg: 'Свободен в смисъл „незает“, не „безплатен“ — безплатното е kostenlos или gratis.',
    },
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 2 — free time
 * ------------------------------------------------------------------ */

const FREE_TIME: VocabEntry[] = [
  {
    id: 'v-hobby',
    german: 'Hobby',
    display: 'das Hobby',
    article: 'das',
    gender: 'n',
    plural: 'die Hobbys',
    wordType: 'noun',
    translation: { en: 'hobby', bg: 'хоби' },
    pronunciation: { en: 'HO-bee', bg: 'ХО-би' },
    example: {
      de: 'Mein Hobby ist Musik.',
      gloss: { en: 'My hobby is music.', bg: 'Хобито ми е музика.' },
    },
    tags: ['free-time'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 1,
  },
  {
    id: 'v-lesen',
    german: 'lesen',
    display: 'lesen',
    wordType: 'verb',
    translation: { en: 'to read', bg: 'чета' },
    pronunciation: { en: 'LAY-zen', bg: 'ЛЕ-зен' },
    example: {
      de: 'Ich lese gern.',
      gloss: { en: 'I like reading.', bg: 'Обичам да чета.' },
    },
    tags: ['verb', 'free-time', 'irregular'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'Irregular: du liest, er liest. The e becomes ie, and the du form does not add a second s.',
      bg: 'Неправилен: du liest, er liest. Гласната e става ie, а формата за du не добавя второ s.',
    },
  },
  {
    id: 'v-hoeren',
    german: 'hören',
    display: 'hören',
    wordType: 'verb',
    translation: { en: 'to hear, to listen to', bg: 'слушам, чувам' },
    pronunciation: { en: 'HOE-ren', bg: 'ХЬО-рен' },
    example: {
      de: 'Ich höre gern Musik.',
      gloss: { en: 'I like listening to music.', bg: 'Обичам да слушам музика.' },
    },
    tags: ['verb', 'free-time'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'No preposition: "Ich höre Musik", not "listen to music". The music is a direct object.',
      bg: 'Без предлог: „Ich höre Musik“. Музиката е пряко допълнение, също както в българското „слушам музика“.',
    },
  },
  {
    id: 'v-musik',
    german: 'Musik',
    display: 'die Musik',
    article: 'die',
    gender: 'f',
    wordType: 'noun',
    translation: { en: 'music', bg: 'музика' },
    pronunciation: { en: 'moo-ZEEK', bg: 'му-ЗИК' },
    example: {
      de: 'Die Musik ist sehr laut.',
      gloss: { en: 'The music is very loud.', bg: 'Музиката е много силна.' },
    },
    tags: ['free-time'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'Stress on the second syllable: moo-ZEEK, not MOO-sik.',
      bg: 'Ударението е на втората сричка: му-ЗИК.',
    },
  },
  {
    id: 'v-sport',
    german: 'Sport',
    display: 'der Sport',
    article: 'der',
    gender: 'm',
    wordType: 'noun',
    translation: { en: 'sport, exercise', bg: 'спорт' },
    pronunciation: { en: 'shport', bg: 'щпорт' },
    example: {
      de: 'Ich mache gern Sport.',
      gloss: { en: 'I like doing sport.', bg: 'Обичам да спортувам.' },
    },
    tags: ['free-time'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'German says "Sport machen" — to make sport. The verb is machen, not "do".',
      bg: 'Немският казва „Sport machen“ — буквално „правя спорт“. Глаголът е machen. И помни: st- в началото се чете „щ“.',
    },
  },
  {
    id: 'v-spielen',
    german: 'spielen',
    display: 'spielen',
    wordType: 'verb',
    translation: { en: 'to play', bg: 'играя, свиря' },
    pronunciation: { en: 'SHPEE-len', bg: 'ШПИ-лен' },
    example: {
      de: 'Ich spiele Fußball.',
      gloss: { en: 'I play football.', bg: 'Играя футбол.' },
    },
    tags: ['verb', 'free-time'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      bg: 'Едната немска дума покрива и „играя“, и „свиря“: spielen Fußball, spielen Klavier. Българският използва два различни глагола.',
      en: 'One verb for games and instruments: Fußball spielen, Klavier spielen.',
    },
  },
  {
    id: 'v-schwimmen',
    german: 'schwimmen',
    display: 'schwimmen',
    wordType: 'verb',
    translation: { en: 'to swim', bg: 'плувам' },
    pronunciation: { en: 'SHVIM-men', bg: 'ШВИ-мен' },
    example: {
      de: 'Im Sommer schwimme ich oft.',
      gloss: { en: 'In summer I often swim.', bg: 'През лятото плувам често.' },
    },
    tags: ['verb', 'free-time'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
  },
  {
    id: 'v-tanzen',
    german: 'tanzen',
    display: 'tanzen',
    wordType: 'verb',
    translation: { en: 'to dance', bg: 'танцувам' },
    pronunciation: { en: 'TAN-tsen', bg: 'ТАН-цен' },
    example: {
      de: 'Meine Schwester tanzt gern.',
      gloss: { en: 'My sister likes dancing.', bg: 'Сестра ми обича да танцува.' },
    },
    tags: ['verb', 'free-time'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 2,
    notes: {
      en: 'The du form has just one s: du tanzt, because the z already carries the sound.',
      bg: 'Формата за du е само с едно s: du tanzt, защото z вече носи звука.',
    },
  },
  {
    id: 'v-treffen',
    german: 'treffen',
    display: 'treffen',
    wordType: 'verb',
    translation: { en: 'to meet', bg: 'срещам се с' },
    pronunciation: { en: 'TREF-fen', bg: 'ТРЕ-фен' },
    example: {
      de: 'Ich treffe meine Freunde.',
      gloss: { en: 'I am meeting my friends.', bg: 'Срещам се с приятелите си.' },
    },
    tags: ['verb', 'free-time', 'irregular', 'accusative'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    notes: {
      bg: 'Внимавай със строежа. Българското „срещам се с някого“ иска предлог. Немското treffen не иска нищо — човекът е пряко допълнение: „Ich treffe meinen Freund“. И е неправилен: du triffst, er trifft.',
      en: 'Irregular: du triffst, er trifft. It takes a direct object, so "Ich treffe meinen Freund".',
    },
  },
  {
    id: 'v-fahrrad',
    german: 'Fahrrad',
    display: 'das Fahrrad',
    article: 'das',
    gender: 'n',
    plural: 'die Fahrräder',
    wordType: 'noun',
    translation: { en: 'bicycle', bg: 'велосипед, колело' },
    pronunciation: { en: 'FAHR-raht', bg: 'ФАР-рат' },
    example: {
      de: 'Ich fahre gern Fahrrad.',
      gloss: { en: 'I like cycling.', bg: 'Обичам да карам колело.' },
    },
    tags: ['free-time', 'transport'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'To cycle is "Fahrrad fahren" — literally to drive bicycle, with no article at all.',
      bg: 'Да караш колело е „Fahrrad fahren“ — буквално „карам колело“, без никакъв член.',
    },
  },
  {
    id: 'v-fahren',
    german: 'fahren',
    display: 'fahren',
    wordType: 'verb',
    translation: { en: 'to go (by vehicle), to drive', bg: 'карам, пътувам' },
    pronunciation: { en: 'FAH-ren', bg: 'ФА-рен' },
    example: {
      de: 'Ich fahre nach Berlin.',
      gloss: { en: 'I am going to Berlin.', bg: 'Пътувам за Берлин.' },
    },
    tags: ['verb', 'transport', 'irregular'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 3,
    notes: {
      en: 'Irregular: du fährst, er fährt. German splits going: fahren if a vehicle is involved, gehen on foot.',
      bg: 'Неправилен: du fährst, er fährt. Немският разделя ходенето: fahren с превозно средство, gehen пеша. Българското „отивам“ върши и двете.',
    },
  },
  {
    id: 'v-lieber',
    german: 'lieber',
    display: 'lieber',
    wordType: 'adverb',
    translation: { en: 'rather, prefer to', bg: 'по-скоро, предпочитам' },
    pronunciation: { en: 'LEE-ber', bg: 'ЛИ-бер' },
    example: {
      de: 'Ich lese lieber.',
      gloss: { en: 'I would rather read.', bg: 'Предпочитам да чета.' },
    },
    tags: ['adverb'],
    level: 'a1',
    unitId: U,
    lessonId: L2,
    difficulty: 4,
    related: ['v-gern'],
    notes: {
      en: 'The comparative of gern. gern = I like doing it, lieber = I prefer it, am liebsten = most of all.',
      bg: 'Сравнителната степен на gern. gern = обичам да го правя, lieber = предпочитам, am liebsten = най-много.',
    },
  },
];

/* ------------------------------------------------------------------ *
 * Lesson 3 — joining sentences
 * ------------------------------------------------------------------ */

const CONJUNCTIONS: VocabEntry[] = [
  {
    id: 'v-und',
    german: 'und',
    display: 'und',
    wordType: 'conjunction',
    translation: { en: 'and', bg: 'и' },
    pronunciation: { en: 'oont', bg: 'унт' },
    example: {
      de: 'Ich lese und ich höre Musik.',
      gloss: { en: 'I read and I listen to music.', bg: 'Чета и слушам музика.' },
    },
    tags: ['conjunction'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 1,
  },
  {
    id: 'v-aber',
    german: 'aber',
    display: 'aber',
    wordType: 'conjunction',
    translation: { en: 'but', bg: 'но' },
    pronunciation: { en: 'AH-ber', bg: 'А-бер' },
    example: {
      de: 'Ich arbeite viel, aber ich bin nicht müde.',
      gloss: { en: 'I work a lot, but I am not tired.', bg: 'Работя много, но не съм уморен.' },
    },
    tags: ['conjunction'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-oder',
    german: 'oder',
    display: 'oder',
    wordType: 'conjunction',
    translation: { en: 'or', bg: 'или' },
    pronunciation: { en: 'OH-der', bg: 'О-дер' },
    example: {
      de: 'Trinkst du Tee oder Kaffee?',
      gloss: { en: 'Do you drink tea or coffee?', bg: 'Пиеш ли чай или кафе?' },
    },
    tags: ['conjunction'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 1,
  },
  {
    id: 'v-denn',
    german: 'denn',
    display: 'denn',
    wordType: 'conjunction',
    translation: { en: 'because', bg: 'защото' },
    pronunciation: { en: 'den', bg: 'ден' },
    example: {
      de: 'Ich trinke Kaffee, denn ich bin müde.',
      gloss: { en: 'I am drinking coffee, because I am tired.', bg: 'Пия кафе, защото съм уморен.' },
    },
    tags: ['conjunction'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 4,
    notes: {
      en: 'The easy "because": it changes nothing about the word order. German has another one, weil, which throws the verb to the end — that comes later, and denn buys you time.',
      bg: 'Лесното „защото“: не променя нищо в словореда. Немският има и друго — weil — което хвърля глагола в края. То идва по-късно, а denn ти купува време дотогава.',
    },
  },
  {
    id: 'v-muede',
    german: 'müde',
    display: 'müde',
    wordType: 'adjective',
    translation: { en: 'tired', bg: 'уморен' },
    pronunciation: { en: 'MUE-de', bg: 'МЮ-де' },
    example: {
      de: 'Ich bin sehr müde.',
      gloss: { en: 'I am very tired.', bg: 'Много съм уморен.' },
    },
    tags: ['adjective'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
  },
  {
    id: 'v-viel',
    german: 'viel',
    display: 'viel',
    wordType: 'adverb',
    translation: { en: 'a lot, much', bg: 'много' },
    pronunciation: { en: 'feel', bg: 'фил' },
    example: {
      de: 'Ich arbeite viel.',
      gloss: { en: 'I work a lot.', bg: 'Работя много.' },
    },
    tags: ['adverb'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 2,
    related: ['v-sehr'],
    notes: {
      bg: 'Пак разделянето на българското „много“: viel върви с глагол (arbeite viel) и със съществително (viel Zeit), а sehr — с прилагателно (sehr müde).',
      en: 'viel goes with a verb or a noun; sehr goes with an adjective. "Ich arbeite viel" but "Ich bin sehr müde".',
    },
  },
  {
    id: 'v-zu-hause',
    german: 'zu Hause',
    display: 'zu Hause',
    wordType: 'phrase',
    translation: { en: 'at home', bg: 'вкъщи' },
    pronunciation: { en: 'tsoo HOW-ze', bg: 'цу ХАУ-зе' },
    example: {
      de: 'Am Abend bin ich zu Hause.',
      gloss: { en: 'In the evening I am at home.', bg: 'Вечер съм вкъщи.' },
    },
    tags: ['phrase', 'home'],
    level: 'a1',
    unitId: U,
    lessonId: L3,
    difficulty: 3,
    notes: {
      en: 'Two words, and Hause keeps its capital. "zu Hause" is being at home; "nach Hause" is going home.',
      bg: 'Две думи, а Hause запазва главната буква. „zu Hause“ е да си вкъщи; „nach Hause“ е да се прибираш.',
    },
  },
];

export const WORK_VOCAB: VocabEntry[] = [...WORK, ...FREE_TIME, ...CONJUNCTIONS];
