import type { VocabEntry } from './types.ts';
import { FAMILY_VOCAB } from './vocab/family.ts';
import { GRAMMAR_WORD_VOCAB } from './vocab/grammarWords.ts';
import { HOME_VOCAB } from './vocab/home.ts';
import { NUMBER_VOCAB } from './vocab/numbers.ts';
import { PERSONAL_VOCAB } from './vocab/personal.ts';
import { TIME_VOCAB } from './vocab/time.ts';

/**
 * Vocabulary for the authored Pre-A1 course.
 *
 * German is stored once. `translation` and `pronunciation` are authored for each
 * teaching path, and `notes` carries path-specific pedagogy: the Bulgarian notes
 * point out where German gender disagrees with Bulgarian gender, which is one of
 * the most common sources of article mistakes for Bulgarian speakers.
 *
 * Nouns are always taught as article + noun (`display`), never bare.
 *
 * Units 1 and 2 are listed here; later units live in ./vocab/ modules and are
 * concatenated below, so `VOCABULARY` stays the single source for the whole
 * course.
 */

const UNIT_1_2_VOCAB: VocabEntry[] = [
  /* ---------------- Letters and sounds (Unit 1) ---------------- */
  {
    id: 'v-das-alphabet',
    german: 'Alphabet',
    display: 'das Alphabet',
    article: 'das',
    gender: 'n',
    plural: 'die Alphabete',
    wordType: 'noun',
    translation: { en: 'the alphabet', bg: 'азбуката' },
    pronunciation: { en: 'ahl-fah-BEHT', bg: 'алфа-БЕТ' },
    example: {
      de: 'Das deutsche Alphabet hat 26 Buchstaben.',
      gloss: { en: 'The German alphabet has 26 letters.', bg: 'Немската азбука има 26 букви.' },
    },
    tags: ['alphabet', 'meta'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l1',
    difficulty: 2,
  },
  {
    id: 'v-der-buchstabe',
    german: 'Buchstabe',
    display: 'der Buchstabe',
    article: 'der',
    gender: 'm',
    plural: 'die Buchstaben',
    wordType: 'noun',
    translation: { en: 'the letter (of the alphabet)', bg: 'буквата' },
    pronunciation: { en: 'BOOKH-shtah-buh', bg: 'БУХ-ща-бе' },
    example: {
      de: 'Der erste Buchstabe ist A.',
      gloss: { en: 'The first letter is A.', bg: 'Първата буква е A.' },
    },
    tags: ['alphabet'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l1',
    difficulty: 2,
    notes: {
      bg: 'Внимание: на немски е от мъжки род (der Buchstabe), а на български „буква“ е от женски род.',
      en: 'German has grammatical gender, so this noun comes with "der" attached to it.',
    },
  },

  /* ---------------- Greetings (Unit 2, Lesson 1) ---------------- */
  {
    id: 'v-hallo',
    german: 'Hallo',
    display: 'Hallo',
    wordType: 'interjection',
    translation: { en: 'hello (informal, any time of day)', bg: 'здравей / здрасти (неофициално, по всяко време)' },
    pronunciation: { en: 'HAH-loh', bg: 'ХА-ло' },
    example: { de: 'Hallo, ich bin Teo.', gloss: { en: 'Hello, I am Teo.', bg: 'Здравей, аз съм Тео.' } },
    tags: ['greeting'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l1',
    difficulty: 1,
    related: ['v-guten-tag', 'v-tschuess'],
  },
  {
    id: 'v-guten-morgen',
    german: 'Guten Morgen',
    display: 'Guten Morgen',
    wordType: 'phrase',
    translation: { en: 'good morning (until about 10 or 11)', bg: 'добро утро (до около 10–11 часа)' },
    pronunciation: { en: 'GOO-ten MOR-gen', bg: 'ГУ-тен МОР-ген' },
    example: {
      de: 'Guten Morgen, Frau Weber!',
      gloss: { en: 'Good morning, Mrs Weber!', bg: 'Добро утро, госпожо Вебер!' },
    },
    tags: ['greeting', 'time-of-day'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l1',
    difficulty: 1,
    collocations: [{ de: 'Guten Morgen sagen', gloss: { en: 'to say good morning', bg: 'да кажеш добро утро' } }],
  },
  {
    id: 'v-guten-tag',
    german: 'Guten Tag',
    display: 'Guten Tag',
    wordType: 'phrase',
    translation: { en: 'good day / hello (neutral, polite)', bg: 'добър ден (неутрално, учтиво)' },
    pronunciation: { en: 'GOO-ten TAHK', bg: 'ГУ-тен ТАК' },
    example: {
      de: 'Guten Tag, ich heiße Teo Petrov.',
      gloss: { en: 'Good day, my name is Teo Petrov.', bg: 'Добър ден, казвам се Тео Петров.' },
    },
    tags: ['greeting', 'time-of-day', 'formal'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l1',
    difficulty: 1,
    notes: {
      en: 'This is the safe default with strangers, in shops and at the doctor.',
      bg: 'Това е най-безопасният избор с непознати, в магазин и при лекар.',
    },
  },
  {
    id: 'v-guten-abend',
    german: 'Guten Abend',
    display: 'Guten Abend',
    wordType: 'phrase',
    translation: { en: 'good evening (from about 18:00)', bg: 'добър вечер (от около 18:00)' },
    pronunciation: { en: 'GOO-ten AH-bent', bg: 'ГУ-тен А-бент' },
    example: {
      de: 'Guten Abend! Ein Tisch für zwei, bitte.',
      gloss: { en: 'Good evening! A table for two, please.', bg: 'Добър вечер! Маса за двама, моля.' },
    },
    tags: ['greeting', 'time-of-day'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l1',
    difficulty: 1,
  },
  {
    id: 'v-gute-nacht',
    german: 'Gute Nacht',
    display: 'Gute Nacht',
    wordType: 'phrase',
    translation: { en: 'good night (only when going to bed)', bg: 'лека нощ (само когато си отиваш да спиш)' },
    pronunciation: { en: 'GOO-tuh NAHKHT', bg: 'ГУ-те НАХТ' },
    example: {
      de: 'Gute Nacht, schlaf gut!',
      gloss: { en: 'Good night, sleep well!', bg: 'Лека нощ, приятен сън!' },
    },
    tags: ['greeting', 'farewell', 'time-of-day'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l1',
    difficulty: 2,
    notes: {
      en: 'Note "Gute", not "Guten": Nacht is feminine. This is a goodbye, never a greeting.',
      bg: 'Обърни внимание: „Gute“, не „Guten“ — Nacht е от женски род. Това е сбогуване, не поздрав.',
    },
  },
  {
    id: 'v-tschuess',
    german: 'Tschüss',
    display: 'Tschüss',
    wordType: 'interjection',
    translation: { en: 'bye (informal)', bg: 'чао (неофициално)' },
    pronunciation: { en: 'CHUESS (like "ch" in church + "ue")', bg: 'ЧЮС' },
    example: { de: 'Tschüss, bis morgen!', gloss: { en: 'Bye, see you tomorrow!', bg: 'Чао, до утре!' } },
    tags: ['farewell'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l1',
    difficulty: 2,
  },
  {
    id: 'v-auf-wiedersehen',
    german: 'Auf Wiedersehen',
    display: 'Auf Wiedersehen',
    wordType: 'phrase',
    translation: { en: 'goodbye (formal)', bg: 'довиждане (официално)' },
    pronunciation: { en: 'owf VEE-der-zayn', bg: 'ауф ВИ-дер-зейн' },
    example: {
      de: 'Auf Wiedersehen, Herr Doktor.',
      gloss: { en: 'Goodbye, doctor.', bg: 'Довиждане, докторе.' },
    },
    tags: ['farewell', 'formal'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l1',
    difficulty: 2,
  },
  {
    id: 'v-bis-bald',
    german: 'Bis bald',
    display: 'Bis bald',
    wordType: 'phrase',
    translation: { en: 'see you soon', bg: 'до скоро' },
    pronunciation: { en: 'biss BALT', bg: 'бис БАЛТ' },
    example: { de: 'Bis bald, Anna!', gloss: { en: 'See you soon, Anna!', bg: 'До скоро, Ана!' } },
    tags: ['farewell'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l1',
    difficulty: 2,
  },

  /* ---------------- Politeness (Unit 2, Lesson 2) ---------------- */
  {
    id: 'v-danke',
    german: 'Danke',
    display: 'Danke',
    wordType: 'interjection',
    translation: { en: 'thank you', bg: 'благодаря' },
    pronunciation: { en: 'DAHN-kuh', bg: 'ДАН-ке' },
    example: { de: 'Danke, das ist sehr nett.', gloss: { en: 'Thanks, that is very kind.', bg: 'Благодаря, много мило.' } },
    tags: ['politeness'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l2',
    difficulty: 1,
    collocations: [
      { de: 'Danke schön', gloss: { en: 'thank you very much', bg: 'много благодаря' } },
      { de: 'Vielen Dank', gloss: { en: 'many thanks', bg: 'много благодаря (по-официално)' } },
    ],
  },
  {
    id: 'v-bitte',
    german: 'Bitte',
    display: 'Bitte',
    wordType: 'interjection',
    translation: {
      en: 'please / you’re welcome / here you are',
      bg: 'моля / няма защо / заповядай',
    },
    pronunciation: { en: 'BIT-tuh', bg: 'БИ-те' },
    example: { de: 'Ein Wasser, bitte.', gloss: { en: 'A water, please.', bg: 'Една вода, моля.' } },
    tags: ['politeness'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l2',
    difficulty: 2,
    notes: {
      en: '"Bitte" does three jobs: please, you’re welcome, and here-you-are when handing something over.',
      bg: '„Bitte“ върши три работи: моля, няма защо и заповядай, когато подаваш нещо.',
    },
  },
  {
    id: 'v-entschuldigung',
    german: 'Entschuldigung',
    display: 'die Entschuldigung',
    article: 'die',
    gender: 'f',
    plural: 'die Entschuldigungen',
    wordType: 'noun',
    translation: { en: 'excuse me / sorry', bg: 'извинете / извинявам се' },
    pronunciation: { en: 'ent-SHOOL-di-goong', bg: 'ент-ШУЛ-ди-гунг' },
    example: {
      de: 'Entschuldigung, wo ist der Bahnhof?',
      gloss: { en: 'Excuse me, where is the station?', bg: 'Извинете, къде е гарата?' },
    },
    tags: ['politeness'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l2',
    difficulty: 3,
    notes: {
      en: 'Long word, but you will use it constantly — to apologise and to get someone’s attention.',
      bg: 'Дълга дума, но ще я използваш постоянно — и за извинение, и за да привлечеш внимание.',
    },
  },
  {
    id: 'v-ja',
    german: 'Ja',
    display: 'Ja',
    wordType: 'particle',
    translation: { en: 'yes', bg: 'да' },
    pronunciation: { en: 'YAH', bg: 'Я' },
    example: { de: 'Ja, gern!', gloss: { en: 'Yes, gladly!', bg: 'Да, с удоволствие!' } },
    tags: ['politeness', 'basics'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l2',
    difficulty: 1,
  },
  {
    id: 'v-nein',
    german: 'Nein',
    display: 'Nein',
    wordType: 'particle',
    translation: { en: 'no', bg: 'не' },
    pronunciation: { en: 'NINE (rhymes with "mine")', bg: 'НАЙН' },
    example: { de: 'Nein, danke.', gloss: { en: 'No, thank you.', bg: 'Не, благодаря.' } },
    tags: ['politeness', 'basics'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l2',
    difficulty: 1,
    notes: {
      bg: 'Пази се от смесване: немското „nein“ (не) звучи като българското „найн“, а не като „не“.',
    },
  },
  {
    id: 'v-wie-gehts',
    german: 'Wie geht es dir?',
    display: 'Wie geht es dir?',
    wordType: 'phrase',
    translation: { en: 'How are you? (informal)', bg: 'Как си? (неофициално)' },
    pronunciation: { en: 'vee GAYT es DEER', bg: 'ви ГЕЙТ ес ДИР' },
    example: {
      de: 'Hallo Anna, wie geht es dir?',
      gloss: { en: 'Hi Anna, how are you?', bg: 'Здравей, Ана, как си?' },
    },
    tags: ['politeness', 'smalltalk'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l2',
    difficulty: 3,
    collocations: [
      { de: "Wie geht's?", gloss: { en: 'How’s it going? (very informal)', bg: 'Как е? (много неофициално)' } },
      { de: 'Wie geht es Ihnen?', gloss: { en: 'How are you? (formal)', bg: 'Как сте? (учтиво)' } },
    ],
  },
  {
    id: 'v-gut-danke',
    german: 'Gut, danke.',
    display: 'Gut, danke.',
    wordType: 'phrase',
    translation: { en: 'Fine, thanks.', bg: 'Добре, благодаря.' },
    pronunciation: { en: 'GOOT, DAHN-kuh', bg: 'ГУТ, ДАН-ке' },
    example: {
      de: 'Gut, danke. Und dir?',
      gloss: { en: 'Fine, thanks. And you?', bg: 'Добре, благодаря. А ти?' },
    },
    tags: ['politeness', 'smalltalk'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l2',
    difficulty: 2,
  },

  /* ---------------- Introducing yourself (Unit 2, Lesson 3) ---------------- */
  {
    id: 'v-heissen',
    german: 'heißen',
    display: 'heißen',
    wordType: 'verb',
    translation: { en: 'to be called', bg: 'казвам се, наричам се' },
    pronunciation: { en: 'HY-sen', bg: 'ХАЙ-сен' },
    example: { de: 'Ich heiße Teo.', gloss: { en: 'My name is Teo.', bg: 'Казвам се Тео.' } },
    tags: ['introduction', 'verb'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l3',
    difficulty: 2,
    notes: {
      en: 'German says "I am called Teo", not "My name is Teo" — though both exist.',
      bg: 'Немският казва буквално „наричам се Тео“. Много близко до българското „казвам се“.',
    },
  },
  {
    id: 'v-der-name',
    german: 'Name',
    display: 'der Name',
    article: 'der',
    gender: 'm',
    plural: 'die Namen',
    wordType: 'noun',
    translation: { en: 'the name', bg: 'името' },
    pronunciation: { en: 'NAH-muh', bg: 'НА-ме' },
    example: { de: 'Mein Name ist Teo.', gloss: { en: 'My name is Teo.', bg: 'Името ми е Тео.' } },
    tags: ['introduction'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l3',
    difficulty: 2,
    notes: {
      bg: 'Родът не съвпада: на немски der Name (мъжки), на български „име“ е от среден род.',
      en: 'English has no gender here, so "der" has to be learnt together with the word.',
    },
  },
  {
    id: 'v-sein-verb',
    german: 'sein',
    display: 'sein',
    wordType: 'verb',
    translation: { en: 'to be', bg: 'съм, бъда' },
    pronunciation: { en: 'ZINE', bg: 'ЗАЙН' },
    example: { de: 'Ich bin Teo.', gloss: { en: 'I am Teo.', bg: 'Аз съм Тео.' } },
    tags: ['introduction', 'verb', 'irregular'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l3',
    difficulty: 3,
    notes: {
      en: 'Completely irregular: ich bin, du bist, er ist. Learn the forms, not a rule.',
      bg: 'Напълно неправилен: ich bin, du bist, er ist. Учи формите, не правило.',
    },
  },
  {
    id: 'v-wie-heisst-du',
    german: 'Wie heißt du?',
    display: 'Wie heißt du?',
    wordType: 'phrase',
    translation: { en: 'What is your name? (informal)', bg: 'Как се казваш? (неофициално)' },
    pronunciation: { en: 'vee HYST doo', bg: 'ви ХАЙСТ ду' },
    example: {
      de: 'Hallo! Wie heißt du?',
      gloss: { en: 'Hi! What is your name?', bg: 'Здравей! Как се казваш?' },
    },
    tags: ['introduction', 'question', 'informal'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l3',
    difficulty: 2,
  },
  {
    id: 'v-wie-heissen-sie',
    german: 'Wie heißen Sie?',
    display: 'Wie heißen Sie?',
    wordType: 'phrase',
    translation: { en: 'What is your name? (formal)', bg: 'Как се казвате? (учтиво)' },
    pronunciation: { en: 'vee HY-sen ZEE', bg: 'ви ХАЙ-сен ЗИ' },
    example: {
      de: 'Guten Tag, wie heißen Sie?',
      gloss: { en: 'Good day, what is your name?', bg: 'Добър ден, как се казвате?' },
    },
    tags: ['introduction', 'question', 'formal'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l3',
    difficulty: 3,
    notes: {
      en: 'Sie is always capitalised when it means formal "you".',
      bg: 'Учтивото „Sie“ винаги се пише с главна буква — точно както българското „Вие“.',
    },
  },

  /* ---------------- Origin and residence (Unit 2, Lesson 4) ---------------- */
  {
    id: 'v-kommen',
    german: 'kommen',
    display: 'kommen',
    wordType: 'verb',
    translation: { en: 'to come', bg: 'идвам' },
    pronunciation: { en: 'KOM-men', bg: 'КО-мен' },
    example: { de: 'Ich komme aus Bulgarien.', gloss: { en: 'I come from Bulgaria.', bg: 'Аз съм от България.' } },
    tags: ['origin', 'verb'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l4',
    difficulty: 1,
  },
  {
    id: 'v-wohnen',
    german: 'wohnen',
    display: 'wohnen',
    wordType: 'verb',
    translation: { en: 'to live, to reside', bg: 'живея (на определено място)' },
    pronunciation: { en: 'VOH-nen', bg: 'ВО-нен' },
    example: { de: 'Ich wohne in Hamburg.', gloss: { en: 'I live in Hamburg.', bg: 'Живея в Хамбург.' } },
    tags: ['residence', 'verb'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l4',
    difficulty: 1,
    related: ['v-leben'],
    notes: {
      en: '"wohnen" is about the address you live at; "leben" is about life in general.',
      bg: '„wohnen“ е за адреса, на който живееш; „leben“ е за живота като цяло.',
    },
  },
  {
    id: 'v-leben',
    german: 'leben',
    display: 'leben',
    wordType: 'verb',
    translation: { en: 'to live (in general)', bg: 'живея (като цяло)' },
    pronunciation: { en: 'LAY-ben', bg: 'ЛЕ-бен' },
    example: {
      de: 'Ich lebe seit zwei Jahren in Deutschland.',
      gloss: { en: 'I have been living in Germany for two years.', bg: 'Живея в Германия от две години.' },
    },
    tags: ['residence', 'verb'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l4',
    difficulty: 2,
    related: ['v-wohnen'],
  },
  {
    id: 'v-woher-kommst-du',
    german: 'Woher kommst du?',
    display: 'Woher kommst du?',
    wordType: 'phrase',
    translation: { en: 'Where are you from? (informal)', bg: 'Откъде си? (неофициално)' },
    pronunciation: { en: 'vo-HAIR komst doo', bg: 'во-ХЕР комст ду' },
    example: {
      de: 'Woher kommst du? — Aus Bulgarien.',
      gloss: { en: 'Where are you from? — From Bulgaria.', bg: 'Откъде си? — От България.' },
    },
    tags: ['origin', 'question', 'informal'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l4',
    difficulty: 2,
  },
  {
    id: 'v-wo-wohnst-du',
    german: 'Wo wohnst du?',
    display: 'Wo wohnst du?',
    wordType: 'phrase',
    translation: { en: 'Where do you live? (informal)', bg: 'Къде живееш? (неофициално)' },
    pronunciation: { en: 'vo VOHNST doo', bg: 'во ВОНСТ ду' },
    example: {
      de: 'Wo wohnst du jetzt?',
      gloss: { en: 'Where do you live now?', bg: 'Къде живееш сега?' },
    },
    tags: ['residence', 'question', 'informal'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l4',
    difficulty: 2,
    notes: {
      en: 'Two similar question words: wo = where (location), woher = where from (origin).',
      bg: 'Две близки въпросителни думи: wo = къде (място), woher = откъде (произход).',
    },
  },
  {
    id: 'v-deutschland',
    german: 'Deutschland',
    display: 'Deutschland',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'Germany', bg: 'Германия' },
    pronunciation: { en: 'DOYTCH-lahnt', bg: 'ДОЙЧ-ланд' },
    example: {
      de: 'Ich wohne in Deutschland.',
      gloss: { en: 'I live in Germany.', bg: 'Живея в Германия.' },
    },
    tags: ['country'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l4',
    difficulty: 1,
    notes: {
      en: 'Most country names take no article: "in Deutschland", not "in dem Deutschland".',
      bg: 'Повечето имена на държави са без член: „in Deutschland“, а не „in dem Deutschland“.',
    },
  },
  {
    id: 'v-bulgarien',
    german: 'Bulgarien',
    display: 'Bulgarien',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'Bulgaria', bg: 'България' },
    pronunciation: { en: 'bool-GAH-ree-en', bg: 'бул-ГА-ри-ен' },
    example: {
      de: 'Ich komme aus Bulgarien.',
      gloss: { en: 'I come from Bulgaria.', bg: 'Аз съм от България.' },
    },
    tags: ['country'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l4',
    difficulty: 1,
  },
  {
    id: 'v-die-stadt',
    german: 'Stadt',
    display: 'die Stadt',
    article: 'die',
    gender: 'f',
    plural: 'die Städte',
    wordType: 'noun',
    translation: { en: 'the city, the town', bg: 'градът' },
    pronunciation: { en: 'SHTAHT', bg: 'ЩАТ' },
    example: {
      de: 'Hamburg ist eine schöne Stadt.',
      gloss: { en: 'Hamburg is a beautiful city.', bg: 'Хамбург е красив град.' },
    },
    tags: ['places'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l4',
    difficulty: 2,
    notes: {
      bg: 'Родът не съвпада: die Stadt е от женски род, а българското „град“ е от мъжки род.',
      en: 'The plural changes the vowel: die Stadt → die Städte.',
    },
  },
  {
    id: 'v-die-sprache',
    german: 'Sprache',
    display: 'die Sprache',
    article: 'die',
    gender: 'f',
    plural: 'die Sprachen',
    wordType: 'noun',
    translation: { en: 'the language', bg: 'езикът' },
    pronunciation: { en: 'SHPRAH-khuh', bg: 'ШПРА-хе' },
    example: {
      de: 'Deutsch ist eine schöne Sprache.',
      gloss: { en: 'German is a beautiful language.', bg: 'Немският е красив език.' },
    },
    tags: ['language'],
    level: 'pre-a1',
    unitId: 'pre-a1-u2',
    lessonId: 'pre-a1-u2-l4',
    difficulty: 2,
    notes: {
      bg: 'Родът не съвпада: die Sprache е от женски род, а българското „език“ е от мъжки род.',
    },
  },

  /* ---------------- Nouns for the article / capitalisation lesson ---------------- */
  {
    id: 'v-das-haus',
    german: 'Haus',
    display: 'das Haus',
    article: 'das',
    gender: 'n',
    plural: 'die Häuser',
    wordType: 'noun',
    translation: { en: 'the house', bg: 'къщата' },
    pronunciation: { en: 'HOWSS', bg: 'ХАУС' },
    example: { de: 'Das Haus ist groß.', gloss: { en: 'The house is big.', bg: 'Къщата е голяма.' } },
    tags: ['home', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 2,
    notes: {
      bg: 'Родът не съвпада: das Haus е от среден род, а българското „къща“ е от женски род. Учи винаги „das Haus“, не само „Haus“.',
      en: 'English has no gender, so the article is extra information you have to store with the word.',
    },
  },
  {
    id: 'v-der-tisch',
    german: 'Tisch',
    display: 'der Tisch',
    article: 'der',
    gender: 'm',
    plural: 'die Tische',
    wordType: 'noun',
    translation: { en: 'the table', bg: 'масата' },
    pronunciation: { en: 'TISH', bg: 'ТИШ' },
    example: { de: 'Der Tisch ist groß.', gloss: { en: 'The table is big.', bg: 'Масата е голяма.' } },
    tags: ['home', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 2,
    notes: {
      bg: 'Родът не съвпада: der Tisch е от мъжки род, а българското „маса“ е от женски род.',
    },
  },
  {
    id: 'v-die-tochter',
    german: 'Tochter',
    display: 'die Tochter',
    article: 'die',
    gender: 'f',
    plural: 'die Töchter',
    wordType: 'noun',
    translation: { en: 'the daughter', bg: 'дъщерята' },
    pronunciation: { en: 'TOKH-ter', bg: 'ТОХ-тер' },
    example: {
      de: 'Ich habe eine Tochter.',
      gloss: { en: 'I have a daughter.', bg: 'Имам една дъщеря.' },
    },
    tags: ['family', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 2,
    notes: {
      bg: 'Тук родът съвпада: и die Tochter, и „дъщеря“ са от женски род. Внимавай с множественото: die Töchter.',
      en: 'The plural only changes the vowel: die Tochter → die Töchter.',
    },
  },
  {
    id: 'v-der-sohn',
    german: 'Sohn',
    display: 'der Sohn',
    article: 'der',
    gender: 'm',
    plural: 'die Söhne',
    wordType: 'noun',
    translation: { en: 'the son', bg: 'синът' },
    pronunciation: { en: 'ZOHN', bg: 'ЗОН' },
    example: { de: 'Mein Sohn heißt Niko.', gloss: { en: 'My son is called Niko.', bg: 'Синът ми се казва Нико.' } },
    tags: ['family', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 2,
  },
  {
    id: 'v-das-buch',
    german: 'Buch',
    display: 'das Buch',
    article: 'das',
    gender: 'n',
    plural: 'die Bücher',
    wordType: 'noun',
    translation: { en: 'the book', bg: 'книгата' },
    pronunciation: { en: 'BOOKH', bg: 'БУХ' },
    example: { de: 'Das Buch ist neu.', gloss: { en: 'The book is new.', bg: 'Книгата е нова.' } },
    tags: ['objects', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 2,
    notes: {
      bg: 'Родът не съвпада: das Buch е от среден род, а „книга“ е от женски род.',
    },
  },
  {
    id: 'v-die-frau',
    german: 'Frau',
    display: 'die Frau',
    article: 'die',
    gender: 'f',
    plural: 'die Frauen',
    wordType: 'noun',
    translation: { en: 'the woman / Mrs', bg: 'жената / госпожа' },
    pronunciation: { en: 'FROW', bg: 'ФРАУ' },
    example: { de: 'Guten Tag, Frau Weber.', gloss: { en: 'Good day, Mrs Weber.', bg: 'Добър ден, госпожо Вебер.' } },
    tags: ['people', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 1,
  },
  {
    id: 'v-der-mann',
    german: 'Mann',
    display: 'der Mann',
    article: 'der',
    gender: 'm',
    plural: 'die Männer',
    wordType: 'noun',
    translation: { en: 'the man', bg: 'мъжът' },
    pronunciation: { en: 'MAHN', bg: 'МАН' },
    example: { de: 'Der Mann heißt Herr Weber.', gloss: { en: 'The man is called Mr Weber.', bg: 'Мъжът се казва господин Вебер.' } },
    tags: ['people', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 1,
  },
  {
    id: 'v-das-kind',
    german: 'Kind',
    display: 'das Kind',
    article: 'das',
    gender: 'n',
    plural: 'die Kinder',
    wordType: 'noun',
    translation: { en: 'the child', bg: 'детето' },
    pronunciation: { en: 'KINT', bg: 'КИНД' },
    example: { de: 'Das Kind ist drei Jahre alt.', gloss: { en: 'The child is three years old.', bg: 'Детето е на три години.' } },
    tags: ['family', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 1,
    notes: {
      bg: 'Тук родът съвпада: das Kind и „дете“ са от среден род.',
    },
  },
  {
    id: 'v-der-hund',
    german: 'Hund',
    display: 'der Hund',
    article: 'der',
    gender: 'm',
    plural: 'die Hunde',
    wordType: 'noun',
    translation: { en: 'the dog', bg: 'кучето' },
    pronunciation: { en: 'HOONT', bg: 'ХУНД' },
    example: { de: 'Der Hund heißt Rex.', gloss: { en: 'The dog is called Rex.', bg: 'Кучето се казва Рекс.' } },
    tags: ['animals', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 2,
    notes: {
      bg: 'Родът не съвпада: der Hund е от мъжки род, а „куче“ е от среден род.',
    },
  },
  {
    id: 'v-die-katze',
    german: 'Katze',
    display: 'die Katze',
    article: 'die',
    gender: 'f',
    plural: 'die Katzen',
    wordType: 'noun',
    translation: { en: 'the cat', bg: 'котката' },
    pronunciation: { en: 'KAT-suh', bg: 'КА-це' },
    example: { de: 'Die Katze schläft.', gloss: { en: 'The cat is sleeping.', bg: 'Котката спи.' } },
    tags: ['animals', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 2,
    notes: {
      bg: 'Тук родът съвпада: die Katze и „котка“ са от женски род.',
    },
  },
  {
    id: 'v-das-wasser',
    german: 'Wasser',
    display: 'das Wasser',
    article: 'das',
    gender: 'n',
    wordType: 'noun',
    translation: { en: 'the water', bg: 'водата' },
    pronunciation: { en: 'VAH-ser', bg: 'ВА-сер' },
    example: { de: 'Ein Wasser, bitte.', gloss: { en: 'A water, please.', bg: 'Една вода, моля.' } },
    tags: ['food', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 2,
    notes: {
      bg: 'Родът не съвпада: das Wasser е от среден род, а „вода“ е от женски род.',
    },
  },
  {
    id: 'v-das-maedchen',
    german: 'Mädchen',
    display: 'das Mädchen',
    article: 'das',
    gender: 'n',
    plural: 'die Mädchen',
    wordType: 'noun',
    translation: { en: 'the girl', bg: 'момичето' },
    pronunciation: { en: 'MAYT-khen', bg: 'МЕТ-хен' },
    example: { de: 'Das Mädchen heißt Lena.', gloss: { en: 'The girl is called Lena.', bg: 'Момичето се казва Лена.' } },
    tags: ['people', 'noun-gender'],
    level: 'pre-a1',
    unitId: 'pre-a1-u1',
    lessonId: 'pre-a1-u1-l2',
    difficulty: 3,
    notes: {
      en: 'Every noun ending in -chen is neuter, even when the person is female. That is grammar, not biology.',
      bg: 'Всяко съществително на -chen е от среден род, дори когато човекът е от женски пол. Точно като българското „момиче“.',
    },
  },
];

export const VOCABULARY: VocabEntry[] = [
  ...UNIT_1_2_VOCAB,
  ...NUMBER_VOCAB,
  ...PERSONAL_VOCAB,
  ...TIME_VOCAB,
  ...GRAMMAR_WORD_VOCAB,
  ...FAMILY_VOCAB,
  ...HOME_VOCAB,
];

const BY_ID = new Map(VOCABULARY.map((entry) => [entry.id, entry]));
const BY_GERMAN = new Map(VOCABULARY.map((entry) => [entry.german.toLowerCase(), entry]));

export function vocabById(id: string): VocabEntry | undefined {
  return BY_ID.get(id);
}

export function vocabByGerman(german: string): VocabEntry | undefined {
  return BY_GERMAN.get(german.toLowerCase());
}

export function vocabForLesson(lessonId: string): VocabEntry[] {
  return VOCABULARY.filter((entry) => entry.lessonId === lessonId);
}
